//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var PgCursors = newPgCursorsTable()

type PgCursorsTable struct {
	postgres.Table

	//Columns
	Name         postgres.ColumnString
	Statement    postgres.ColumnString
	IsHoldable   postgres.ColumnBool
	IsBinary     postgres.ColumnBool
	IsScrollable postgres.ColumnBool
	CreationTime postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgCursorsTable with assigned alias
func (a *PgCursorsTable) AS(alias string) *PgCursorsTable {
	aliasTable := newPgCursorsTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgCursorsTable() *PgCursorsTable {
	var (
		NameColumn         = postgres.StringColumn("name")
		StatementColumn    = postgres.StringColumn("statement")
		IsHoldableColumn   = postgres.BoolColumn("is_holdable")
		IsBinaryColumn     = postgres.BoolColumn("is_binary")
		IsScrollableColumn = postgres.BoolColumn("is_scrollable")
		CreationTimeColumn = postgres.TimestampzColumn("creation_time")
	)

	return &PgCursorsTable{
		Table: postgres.NewTable("pg_catalog", "pg_cursors", NameColumn, StatementColumn, IsHoldableColumn, IsBinaryColumn, IsScrollableColumn, CreationTimeColumn),

		//Columns
		Name:         NameColumn,
		Statement:    StatementColumn,
		IsHoldable:   IsHoldableColumn,
		IsBinary:     IsBinaryColumn,
		IsScrollable: IsScrollableColumn,
		CreationTime: CreationTimeColumn,

		AllColumns:     postgres.ColumnList{NameColumn, StatementColumn, IsHoldableColumn, IsBinaryColumn, IsScrollableColumn, CreationTimeColumn},
		MutableColumns: postgres.ColumnList{NameColumn, StatementColumn, IsHoldableColumn, IsBinaryColumn, IsScrollableColumn, CreationTimeColumn},
	}
}
