//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgIndexes = newPgIndexesTable()

type pgIndexesTable struct {
	postgres.Table

	//Columns
	Schemaname postgres.ColumnString
	Tablename  postgres.ColumnString
	Indexname  postgres.ColumnString
	Tablespace postgres.ColumnString
	Indexdef   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgIndexesTable struct {
	pgIndexesTable

	EXCLUDED pgIndexesTable
}

// AS creates new PgIndexesTable with assigned alias
func (a *PgIndexesTable) AS(alias string) *PgIndexesTable {
	aliasTable := newPgIndexesTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgIndexesTable() *PgIndexesTable {
	return &PgIndexesTable{
		pgIndexesTable: newPgIndexesTableImpl("pg_catalog", "pg_indexes"),
		EXCLUDED:       newPgIndexesTableImpl("", "excluded"),
	}
}

func newPgIndexesTableImpl(schemaName, tableName string) pgIndexesTable {
	var (
		SchemanameColumn = postgres.StringColumn("schemaname")
		TablenameColumn  = postgres.StringColumn("tablename")
		IndexnameColumn  = postgres.StringColumn("indexname")
		TablespaceColumn = postgres.StringColumn("tablespace")
		IndexdefColumn   = postgres.StringColumn("indexdef")
		allColumns       = postgres.ColumnList{SchemanameColumn, TablenameColumn, IndexnameColumn, TablespaceColumn, IndexdefColumn}
		mutableColumns   = postgres.ColumnList{SchemanameColumn, TablenameColumn, IndexnameColumn, TablespaceColumn, IndexdefColumn}
	)

	return pgIndexesTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Schemaname: SchemanameColumn,
		Tablename:  TablenameColumn,
		Indexname:  IndexnameColumn,
		Tablespace: TablespaceColumn,
		Indexdef:   IndexdefColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
