//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var PgStatSubscription = newPgStatSubscriptionTable()

type PgStatSubscriptionTable struct {
	postgres.Table

	//Columns
	Subid              postgres.ColumnString
	Subname            postgres.ColumnString
	Pid                postgres.ColumnInteger
	Relid              postgres.ColumnString
	ReceivedLsn        postgres.ColumnString
	LastMsgSendTime    postgres.ColumnTimestampz
	LastMsgReceiptTime postgres.ColumnTimestampz
	LatestEndLsn       postgres.ColumnString
	LatestEndTime      postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgStatSubscriptionTable with assigned alias
func (a *PgStatSubscriptionTable) AS(alias string) *PgStatSubscriptionTable {
	aliasTable := newPgStatSubscriptionTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgStatSubscriptionTable() *PgStatSubscriptionTable {
	var (
		SubidColumn              = postgres.StringColumn("subid")
		SubnameColumn            = postgres.StringColumn("subname")
		PidColumn                = postgres.IntegerColumn("pid")
		RelidColumn              = postgres.StringColumn("relid")
		ReceivedLsnColumn        = postgres.StringColumn("received_lsn")
		LastMsgSendTimeColumn    = postgres.TimestampzColumn("last_msg_send_time")
		LastMsgReceiptTimeColumn = postgres.TimestampzColumn("last_msg_receipt_time")
		LatestEndLsnColumn       = postgres.StringColumn("latest_end_lsn")
		LatestEndTimeColumn      = postgres.TimestampzColumn("latest_end_time")
	)

	return &PgStatSubscriptionTable{
		Table: postgres.NewTable("pg_catalog", "pg_stat_subscription", SubidColumn, SubnameColumn, PidColumn, RelidColumn, ReceivedLsnColumn, LastMsgSendTimeColumn, LastMsgReceiptTimeColumn, LatestEndLsnColumn, LatestEndTimeColumn),

		//Columns
		Subid:              SubidColumn,
		Subname:            SubnameColumn,
		Pid:                PidColumn,
		Relid:              RelidColumn,
		ReceivedLsn:        ReceivedLsnColumn,
		LastMsgSendTime:    LastMsgSendTimeColumn,
		LastMsgReceiptTime: LastMsgReceiptTimeColumn,
		LatestEndLsn:       LatestEndLsnColumn,
		LatestEndTime:      LatestEndTimeColumn,

		AllColumns:     postgres.ColumnList{SubidColumn, SubnameColumn, PidColumn, RelidColumn, ReceivedLsnColumn, LastMsgSendTimeColumn, LastMsgReceiptTimeColumn, LatestEndLsnColumn, LatestEndTimeColumn},
		MutableColumns: postgres.ColumnList{SubidColumn, SubnameColumn, PidColumn, RelidColumn, ReceivedLsnColumn, LastMsgSendTimeColumn, LastMsgReceiptTimeColumn, LatestEndLsnColumn, LatestEndTimeColumn},
	}
}
