//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var PgSeclabels = newPgSeclabelsTable()

type PgSeclabelsTable struct {
	postgres.Table

	//Columns
	Objoid       postgres.ColumnString
	Classoid     postgres.ColumnString
	Objsubid     postgres.ColumnInteger
	Objtype      postgres.ColumnString
	Objnamespace postgres.ColumnString
	Objname      postgres.ColumnString
	Provider     postgres.ColumnString
	Label        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgSeclabelsTable with assigned alias
func (a *PgSeclabelsTable) AS(alias string) *PgSeclabelsTable {
	aliasTable := newPgSeclabelsTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgSeclabelsTable() *PgSeclabelsTable {
	var (
		ObjoidColumn       = postgres.StringColumn("objoid")
		ClassoidColumn     = postgres.StringColumn("classoid")
		ObjsubidColumn     = postgres.IntegerColumn("objsubid")
		ObjtypeColumn      = postgres.StringColumn("objtype")
		ObjnamespaceColumn = postgres.StringColumn("objnamespace")
		ObjnameColumn      = postgres.StringColumn("objname")
		ProviderColumn     = postgres.StringColumn("provider")
		LabelColumn        = postgres.StringColumn("label")
	)

	return &PgSeclabelsTable{
		Table: postgres.NewTable("pg_catalog", "pg_seclabels", ObjoidColumn, ClassoidColumn, ObjsubidColumn, ObjtypeColumn, ObjnamespaceColumn, ObjnameColumn, ProviderColumn, LabelColumn),

		//Columns
		Objoid:       ObjoidColumn,
		Classoid:     ClassoidColumn,
		Objsubid:     ObjsubidColumn,
		Objtype:      ObjtypeColumn,
		Objnamespace: ObjnamespaceColumn,
		Objname:      ObjnameColumn,
		Provider:     ProviderColumn,
		Label:        LabelColumn,

		AllColumns:     postgres.ColumnList{ObjoidColumn, ClassoidColumn, ObjsubidColumn, ObjtypeColumn, ObjnamespaceColumn, ObjnameColumn, ProviderColumn, LabelColumn},
		MutableColumns: postgres.ColumnList{ObjoidColumn, ClassoidColumn, ObjsubidColumn, ObjtypeColumn, ObjnamespaceColumn, ObjnameColumn, ProviderColumn, LabelColumn},
	}
}
