//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgStatActivity = newPgStatActivityTable()

type pgStatActivityTable struct {
	postgres.Table

	//Columns
	Datid           postgres.ColumnString
	Datname         postgres.ColumnString
	Pid             postgres.ColumnInteger
	LeaderPid       postgres.ColumnInteger
	Usesysid        postgres.ColumnString
	Usename         postgres.ColumnString
	ApplicationName postgres.ColumnString
	ClientAddr      postgres.ColumnString
	ClientHostname  postgres.ColumnString
	ClientPort      postgres.ColumnInteger
	BackendStart    postgres.ColumnTimestampz
	XactStart       postgres.ColumnTimestampz
	QueryStart      postgres.ColumnTimestampz
	StateChange     postgres.ColumnTimestampz
	WaitEventType   postgres.ColumnString
	WaitEvent       postgres.ColumnString
	State           postgres.ColumnString
	BackendXid      postgres.ColumnString
	BackendXmin     postgres.ColumnString
	Query           postgres.ColumnString
	BackendType     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgStatActivityTable struct {
	pgStatActivityTable

	EXCLUDED pgStatActivityTable
}

// AS creates new PgStatActivityTable with assigned alias
func (a *PgStatActivityTable) AS(alias string) *PgStatActivityTable {
	aliasTable := newPgStatActivityTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgStatActivityTable() *PgStatActivityTable {
	return &PgStatActivityTable{
		pgStatActivityTable: newPgStatActivityTableImpl("pg_catalog", "pg_stat_activity"),
		EXCLUDED:            newPgStatActivityTableImpl("", "excluded"),
	}
}

func newPgStatActivityTableImpl(schemaName, tableName string) pgStatActivityTable {
	var (
		DatidColumn           = postgres.StringColumn("datid")
		DatnameColumn         = postgres.StringColumn("datname")
		PidColumn             = postgres.IntegerColumn("pid")
		LeaderPidColumn       = postgres.IntegerColumn("leader_pid")
		UsesysidColumn        = postgres.StringColumn("usesysid")
		UsenameColumn         = postgres.StringColumn("usename")
		ApplicationNameColumn = postgres.StringColumn("application_name")
		ClientAddrColumn      = postgres.StringColumn("client_addr")
		ClientHostnameColumn  = postgres.StringColumn("client_hostname")
		ClientPortColumn      = postgres.IntegerColumn("client_port")
		BackendStartColumn    = postgres.TimestampzColumn("backend_start")
		XactStartColumn       = postgres.TimestampzColumn("xact_start")
		QueryStartColumn      = postgres.TimestampzColumn("query_start")
		StateChangeColumn     = postgres.TimestampzColumn("state_change")
		WaitEventTypeColumn   = postgres.StringColumn("wait_event_type")
		WaitEventColumn       = postgres.StringColumn("wait_event")
		StateColumn           = postgres.StringColumn("state")
		BackendXidColumn      = postgres.StringColumn("backend_xid")
		BackendXminColumn     = postgres.StringColumn("backend_xmin")
		QueryColumn           = postgres.StringColumn("query")
		BackendTypeColumn     = postgres.StringColumn("backend_type")
		allColumns            = postgres.ColumnList{DatidColumn, DatnameColumn, PidColumn, LeaderPidColumn, UsesysidColumn, UsenameColumn, ApplicationNameColumn, ClientAddrColumn, ClientHostnameColumn, ClientPortColumn, BackendStartColumn, XactStartColumn, QueryStartColumn, StateChangeColumn, WaitEventTypeColumn, WaitEventColumn, StateColumn, BackendXidColumn, BackendXminColumn, QueryColumn, BackendTypeColumn}
		mutableColumns        = postgres.ColumnList{DatidColumn, DatnameColumn, PidColumn, LeaderPidColumn, UsesysidColumn, UsenameColumn, ApplicationNameColumn, ClientAddrColumn, ClientHostnameColumn, ClientPortColumn, BackendStartColumn, XactStartColumn, QueryStartColumn, StateChangeColumn, WaitEventTypeColumn, WaitEventColumn, StateColumn, BackendXidColumn, BackendXminColumn, QueryColumn, BackendTypeColumn}
	)

	return pgStatActivityTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Datid:           DatidColumn,
		Datname:         DatnameColumn,
		Pid:             PidColumn,
		LeaderPid:       LeaderPidColumn,
		Usesysid:        UsesysidColumn,
		Usename:         UsenameColumn,
		ApplicationName: ApplicationNameColumn,
		ClientAddr:      ClientAddrColumn,
		ClientHostname:  ClientHostnameColumn,
		ClientPort:      ClientPortColumn,
		BackendStart:    BackendStartColumn,
		XactStart:       XactStartColumn,
		QueryStart:      QueryStartColumn,
		StateChange:     StateChangeColumn,
		WaitEventType:   WaitEventTypeColumn,
		WaitEvent:       WaitEventColumn,
		State:           StateColumn,
		BackendXid:      BackendXidColumn,
		BackendXmin:     BackendXminColumn,
		Query:           QueryColumn,
		BackendType:     BackendTypeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
