//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgStatBgwriter = newPgStatBgwriterTable()

type pgStatBgwriterTable struct {
	postgres.Table

	//Columns
	CheckpointsTimed    postgres.ColumnInteger
	CheckpointsReq      postgres.ColumnInteger
	CheckpointWriteTime postgres.ColumnFloat
	CheckpointSyncTime  postgres.ColumnFloat
	BuffersCheckpoint   postgres.ColumnInteger
	BuffersClean        postgres.ColumnInteger
	MaxwrittenClean     postgres.ColumnInteger
	BuffersBackend      postgres.ColumnInteger
	BuffersBackendFsync postgres.ColumnInteger
	BuffersAlloc        postgres.ColumnInteger
	StatsReset          postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgStatBgwriterTable struct {
	pgStatBgwriterTable

	EXCLUDED pgStatBgwriterTable
}

// AS creates new PgStatBgwriterTable with assigned alias
func (a *PgStatBgwriterTable) AS(alias string) *PgStatBgwriterTable {
	aliasTable := newPgStatBgwriterTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgStatBgwriterTable() *PgStatBgwriterTable {
	return &PgStatBgwriterTable{
		pgStatBgwriterTable: newPgStatBgwriterTableImpl("pg_catalog", "pg_stat_bgwriter"),
		EXCLUDED:            newPgStatBgwriterTableImpl("", "excluded"),
	}
}

func newPgStatBgwriterTableImpl(schemaName, tableName string) pgStatBgwriterTable {
	var (
		CheckpointsTimedColumn    = postgres.IntegerColumn("checkpoints_timed")
		CheckpointsReqColumn      = postgres.IntegerColumn("checkpoints_req")
		CheckpointWriteTimeColumn = postgres.FloatColumn("checkpoint_write_time")
		CheckpointSyncTimeColumn  = postgres.FloatColumn("checkpoint_sync_time")
		BuffersCheckpointColumn   = postgres.IntegerColumn("buffers_checkpoint")
		BuffersCleanColumn        = postgres.IntegerColumn("buffers_clean")
		MaxwrittenCleanColumn     = postgres.IntegerColumn("maxwritten_clean")
		BuffersBackendColumn      = postgres.IntegerColumn("buffers_backend")
		BuffersBackendFsyncColumn = postgres.IntegerColumn("buffers_backend_fsync")
		BuffersAllocColumn        = postgres.IntegerColumn("buffers_alloc")
		StatsResetColumn          = postgres.TimestampzColumn("stats_reset")
		allColumns                = postgres.ColumnList{CheckpointsTimedColumn, CheckpointsReqColumn, CheckpointWriteTimeColumn, CheckpointSyncTimeColumn, BuffersCheckpointColumn, BuffersCleanColumn, MaxwrittenCleanColumn, BuffersBackendColumn, BuffersBackendFsyncColumn, BuffersAllocColumn, StatsResetColumn}
		mutableColumns            = postgres.ColumnList{CheckpointsTimedColumn, CheckpointsReqColumn, CheckpointWriteTimeColumn, CheckpointSyncTimeColumn, BuffersCheckpointColumn, BuffersCleanColumn, MaxwrittenCleanColumn, BuffersBackendColumn, BuffersBackendFsyncColumn, BuffersAllocColumn, StatsResetColumn}
	)

	return pgStatBgwriterTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		CheckpointsTimed:    CheckpointsTimedColumn,
		CheckpointsReq:      CheckpointsReqColumn,
		CheckpointWriteTime: CheckpointWriteTimeColumn,
		CheckpointSyncTime:  CheckpointSyncTimeColumn,
		BuffersCheckpoint:   BuffersCheckpointColumn,
		BuffersClean:        BuffersCleanColumn,
		MaxwrittenClean:     MaxwrittenCleanColumn,
		BuffersBackend:      BuffersBackendColumn,
		BuffersBackendFsync: BuffersBackendFsyncColumn,
		BuffersAlloc:        BuffersAllocColumn,
		StatsReset:          StatsResetColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
