//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var PgTables = newPgTablesTable()

type PgTablesTable struct {
	postgres.Table

	//Columns
	Schemaname  postgres.ColumnString
	Tablename   postgres.ColumnString
	Tableowner  postgres.ColumnString
	Tablespace  postgres.ColumnString
	Hasindexes  postgres.ColumnBool
	Hasrules    postgres.ColumnBool
	Hastriggers postgres.ColumnBool
	Rowsecurity postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgTablesTable with assigned alias
func (a *PgTablesTable) AS(alias string) *PgTablesTable {
	aliasTable := newPgTablesTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgTablesTable() *PgTablesTable {
	var (
		SchemanameColumn  = postgres.StringColumn("schemaname")
		TablenameColumn   = postgres.StringColumn("tablename")
		TableownerColumn  = postgres.StringColumn("tableowner")
		TablespaceColumn  = postgres.StringColumn("tablespace")
		HasindexesColumn  = postgres.BoolColumn("hasindexes")
		HasrulesColumn    = postgres.BoolColumn("hasrules")
		HastriggersColumn = postgres.BoolColumn("hastriggers")
		RowsecurityColumn = postgres.BoolColumn("rowsecurity")
	)

	return &PgTablesTable{
		Table: postgres.NewTable("pg_catalog", "pg_tables", SchemanameColumn, TablenameColumn, TableownerColumn, TablespaceColumn, HasindexesColumn, HasrulesColumn, HastriggersColumn, RowsecurityColumn),

		//Columns
		Schemaname:  SchemanameColumn,
		Tablename:   TablenameColumn,
		Tableowner:  TableownerColumn,
		Tablespace:  TablespaceColumn,
		Hasindexes:  HasindexesColumn,
		Hasrules:    HasrulesColumn,
		Hastriggers: HastriggersColumn,
		Rowsecurity: RowsecurityColumn,

		AllColumns:     postgres.ColumnList{SchemanameColumn, TablenameColumn, TableownerColumn, TablespaceColumn, HasindexesColumn, HasrulesColumn, HastriggersColumn, RowsecurityColumn},
		MutableColumns: postgres.ColumnList{SchemanameColumn, TablenameColumn, TableownerColumn, TablespaceColumn, HasindexesColumn, HasrulesColumn, HastriggersColumn, RowsecurityColumn},
	}
}
