//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CharacterSets struct {
	CharacterSetCatalog   *string
	CharacterSetSchema    *string
	CharacterSetName      *string
	CharacterRepertoire   *string
	FormOfUse             *string
	DefaultCollateCatalog *string
	DefaultCollateSchema  *string
	DefaultCollateName    *string
}
