//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ForeignServers struct {
	ForeignServerCatalog      *string
	ForeignServerName         *string
	ForeignDataWrapperCatalog *string
	ForeignDataWrapperName    *string
	ForeignServerType         *string
	ForeignServerVersion      *string
	AuthorizationIdentifier   *string
}
