//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ForeignServerOptions struct {
	ForeignServerCatalog *string
	ForeignServerName    *string
	OptionName           *string
	OptionValue          *string
}
