//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type KeyColumnUsage struct {
	ConstraintCatalog          *string
	ConstraintSchema           *string
	ConstraintName             *string
	TableCatalog               *string
	TableSchema                *string
	TableName                  *string
	ColumnName                 *string
	OrdinalPosition            *int32
	PositionInUniqueConstraint *int32
}
