//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Parameters struct {
	SpecificCatalog        *string
	SpecificSchema         *string
	SpecificName           *string
	OrdinalPosition        *int32
	ParameterMode          *string
	IsResult               *string
	AsLocator              *string
	ParameterName          *string
	DataType               *string
	CharacterMaximumLength *int32
	CharacterOctetLength   *int32
	CharacterSetCatalog    *string
	CharacterSetSchema     *string
	CharacterSetName       *string
	CollationCatalog       *string
	CollationSchema        *string
	CollationName          *string
	NumericPrecision       *int32
	NumericPrecisionRadix  *int32
	NumericScale           *int32
	DatetimePrecision      *int32
	IntervalType           *string
	IntervalPrecision      *int32
	UdtCatalog             *string
	UdtSchema              *string
	UdtName                *string
	ScopeCatalog           *string
	ScopeSchema            *string
	ScopeName              *string
	MaximumCardinality     *int32
	DtdIdentifier          *string
	ParameterDefault       *string
}
