//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type ReferentialConstraints struct {
	ConstraintCatalog       *string
	ConstraintSchema        *string
	ConstraintName          *string
	UniqueConstraintCatalog *string
	UniqueConstraintSchema  *string
	UniqueConstraintName    *string
	MatchOption             *string
	UpdateRule              *string
	DeleteRule              *string
}
