//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RoleRoutineGrants struct {
	Grantor         *string
	Grantee         *string
	SpecificCatalog *string
	SpecificSchema  *string
	SpecificName    *string
	RoutineCatalog  *string
	RoutineSchema   *string
	RoutineName     *string
	PrivilegeType   *string
	IsGrantable     *string
}
