//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RoleUsageGrants struct {
	Grantor       *string
	Grantee       *string
	ObjectCatalog *string
	ObjectSchema  *string
	ObjectName    *string
	ObjectType    *string
	PrivilegeType *string
	IsGrantable   *string
}
