//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type SQLSizing struct {
	SizingID       *int32
	SizingName     *string
	SupportedValue *int32
	Comments       *string
}
