//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Tables struct {
	TableCatalog              *string
	TableSchema               *string
	TableName                 *string
	TableType                 *string
	SelfReferencingColumnName *string
	ReferenceGeneration       *string
	UserDefinedTypeCatalog    *string
	UserDefinedTypeSchema     *string
	UserDefinedTypeName       *string
	IsInsertableInto          *string
	IsTyped                   *string
	CommitAction              *string
}
