//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Triggers struct {
	TriggerCatalog          *string
	TriggerSchema           *string
	TriggerName             *string
	EventManipulation       *string
	EventObjectCatalog      *string
	EventObjectSchema       *string
	EventObjectTable        *string
	ActionOrder             *int32
	ActionCondition         *string
	ActionStatement         *string
	ActionOrientation       *string
	ActionTiming            *string
	ActionReferenceOldTable *string
	ActionReferenceNewTable *string
	ActionReferenceOldRow   *string
	ActionReferenceNewRow   *string
	Created                 *time.Time
}
