/**
 * pgsink
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Import job for a Postgres table
*/
export class Import {
    /**
    * Import was completed at this time
    */
    'completedAt'?: Date;
    /**
    * Import was created at this time
    */
    'createdAt': Date;
    /**
    * Last import error
    */
    'error'?: string;
    /**
    * Count of error attempts
    */
    'errorCount': number;
    /**
    * Import was expired at this time
    */
    'expiredAt'?: Date;
    /**
    * Unique ID for the import
    */
    'id': number;
    /**
    * Timestamp of last error, only reset on error
    */
    'lastErrorAt'?: Date;
    /**
    * Postgres table schema
    */
    'schema': string;
    /**
    * Subscription ID, associating this import to a specific subscription
    */
    'subscriptionId': string;
    /**
    * Postgres table name
    */
    'tableName': string;
    /**
    * Import was last updated at this time
    */
    'updatedAt': Date;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "completedAt",
            "baseName": "completed_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "createdAt",
            "baseName": "created_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "error",
            "baseName": "error",
            "type": "string",
            "format": ""
        },
        {
            "name": "errorCount",
            "baseName": "error_count",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "expiredAt",
            "baseName": "expired_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "lastErrorAt",
            "baseName": "last_error_at",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "string",
            "format": ""
        },
        {
            "name": "subscriptionId",
            "baseName": "subscription_id",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "tableName",
            "baseName": "table_name",
            "type": "string",
            "format": ""
        },
        {
            "name": "updatedAt",
            "baseName": "updated_at",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return Import.attributeTypeMap;
    }
    
    public constructor() {
    }
}

