/**
 * pgsink
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* Postgres table, with sync and import status
*/
export class Table {
    /**
    * Postgres table name
    */
    'name': string;
    /**
    * True if this table is already streaming
    */
    'published': boolean;
    /**
    * Postgres table schema
    */
    'schema': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "published",
            "baseName": "published",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "schema",
            "baseName": "schema",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Table.attributeTypeMap;
    }
    
    public constructor() {
    }
}

