//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var PgTimezoneNames = newPgTimezoneNamesTable()

type PgTimezoneNamesTable struct {
	postgres.Table

	//Columns
	Name      postgres.ColumnString
	Abbrev    postgres.ColumnString
	UtcOffset postgres.ColumnInterval
	IsDst     postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgTimezoneNamesTable with assigned alias
func (a *PgTimezoneNamesTable) AS(alias string) *PgTimezoneNamesTable {
	aliasTable := newPgTimezoneNamesTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgTimezoneNamesTable() *PgTimezoneNamesTable {
	var (
		NameColumn      = postgres.StringColumn("name")
		AbbrevColumn    = postgres.StringColumn("abbrev")
		UtcOffsetColumn = postgres.IntervalColumn("utc_offset")
		IsDstColumn     = postgres.BoolColumn("is_dst")
	)

	return &PgTimezoneNamesTable{
		Table: postgres.NewTable("pg_catalog", "pg_timezone_names", NameColumn, AbbrevColumn, UtcOffsetColumn, IsDstColumn),

		//Columns
		Name:      NameColumn,
		Abbrev:    AbbrevColumn,
		UtcOffset: UtcOffsetColumn,
		IsDst:     IsDstColumn,

		AllColumns:     postgres.ColumnList{NameColumn, AbbrevColumn, UtcOffsetColumn, IsDstColumn},
		MutableColumns: postgres.ColumnList{NameColumn, AbbrevColumn, UtcOffsetColumn, IsDstColumn},
	}
}
