//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var PgUser = newPgUserTable()

type PgUserTable struct {
	postgres.Table

	//Columns
	Usename      postgres.ColumnString
	Usesysid     postgres.ColumnString
	Usecreatedb  postgres.ColumnBool
	Usesuper     postgres.ColumnBool
	Userepl      postgres.ColumnBool
	Usebypassrls postgres.ColumnBool
	Passwd       postgres.ColumnString
	Valuntil     postgres.ColumnTimestampz
	Useconfig    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgUserTable with assigned alias
func (a *PgUserTable) AS(alias string) *PgUserTable {
	aliasTable := newPgUserTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgUserTable() *PgUserTable {
	var (
		UsenameColumn      = postgres.StringColumn("usename")
		UsesysidColumn     = postgres.StringColumn("usesysid")
		UsecreatedbColumn  = postgres.BoolColumn("usecreatedb")
		UsesuperColumn     = postgres.BoolColumn("usesuper")
		UsereplColumn      = postgres.BoolColumn("userepl")
		UsebypassrlsColumn = postgres.BoolColumn("usebypassrls")
		PasswdColumn       = postgres.StringColumn("passwd")
		ValuntilColumn     = postgres.TimestampzColumn("valuntil")
		UseconfigColumn    = postgres.StringColumn("useconfig")
	)

	return &PgUserTable{
		Table: postgres.NewTable("pg_catalog", "pg_user", UsenameColumn, UsesysidColumn, UsecreatedbColumn, UsesuperColumn, UsereplColumn, UsebypassrlsColumn, PasswdColumn, ValuntilColumn, UseconfigColumn),

		//Columns
		Usename:      UsenameColumn,
		Usesysid:     UsesysidColumn,
		Usecreatedb:  UsecreatedbColumn,
		Usesuper:     UsesuperColumn,
		Userepl:      UsereplColumn,
		Usebypassrls: UsebypassrlsColumn,
		Passwd:       PasswdColumn,
		Valuntil:     ValuntilColumn,
		Useconfig:    UseconfigColumn,

		AllColumns:     postgres.ColumnList{UsenameColumn, UsesysidColumn, UsecreatedbColumn, UsesuperColumn, UsereplColumn, UsebypassrlsColumn, PasswdColumn, ValuntilColumn, UseconfigColumn},
		MutableColumns: postgres.ColumnList{UsenameColumn, UsesysidColumn, UsecreatedbColumn, UsesuperColumn, UsereplColumn, UsebypassrlsColumn, PasswdColumn, ValuntilColumn, UseconfigColumn},
	}
}
