//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var ColumnColumnUsage = newColumnColumnUsageTable()

type ColumnColumnUsageTable struct {
	postgres.Table

	//Columns
	TableCatalog    postgres.ColumnString
	TableSchema     postgres.ColumnString
	TableName       postgres.ColumnString
	ColumnName      postgres.ColumnString
	DependentColumn postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new ColumnColumnUsageTable with assigned alias
func (a *ColumnColumnUsageTable) AS(alias string) *ColumnColumnUsageTable {
	aliasTable := newColumnColumnUsageTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newColumnColumnUsageTable() *ColumnColumnUsageTable {
	var (
		TableCatalogColumn    = postgres.StringColumn("table_catalog")
		TableSchemaColumn     = postgres.StringColumn("table_schema")
		TableNameColumn       = postgres.StringColumn("table_name")
		ColumnNameColumn      = postgres.StringColumn("column_name")
		DependentColumnColumn = postgres.StringColumn("dependent_column")
	)

	return &ColumnColumnUsageTable{
		Table: postgres.NewTable("information_schema", "column_column_usage", TableCatalogColumn, TableSchemaColumn, TableNameColumn, ColumnNameColumn, DependentColumnColumn),

		//Columns
		TableCatalog:    TableCatalogColumn,
		TableSchema:     TableSchemaColumn,
		TableName:       TableNameColumn,
		ColumnName:      ColumnNameColumn,
		DependentColumn: DependentColumnColumn,

		AllColumns:     postgres.ColumnList{TableCatalogColumn, TableSchemaColumn, TableNameColumn, ColumnNameColumn, DependentColumnColumn},
		MutableColumns: postgres.ColumnList{TableCatalogColumn, TableSchemaColumn, TableNameColumn, ColumnNameColumn, DependentColumnColumn},
	}
}
