//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var ColumnDomainUsage = newColumnDomainUsageTable()

type ColumnDomainUsageTable struct {
	postgres.Table

	//Columns
	DomainCatalog postgres.ColumnString
	DomainSchema  postgres.ColumnString
	DomainName    postgres.ColumnString
	TableCatalog  postgres.ColumnString
	TableSchema   postgres.ColumnString
	TableName     postgres.ColumnString
	ColumnName    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new ColumnDomainUsageTable with assigned alias
func (a *ColumnDomainUsageTable) AS(alias string) *ColumnDomainUsageTable {
	aliasTable := newColumnDomainUsageTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newColumnDomainUsageTable() *ColumnDomainUsageTable {
	var (
		DomainCatalogColumn = postgres.StringColumn("domain_catalog")
		DomainSchemaColumn  = postgres.StringColumn("domain_schema")
		DomainNameColumn    = postgres.StringColumn("domain_name")
		TableCatalogColumn  = postgres.StringColumn("table_catalog")
		TableSchemaColumn   = postgres.StringColumn("table_schema")
		TableNameColumn     = postgres.StringColumn("table_name")
		ColumnNameColumn    = postgres.StringColumn("column_name")
	)

	return &ColumnDomainUsageTable{
		Table: postgres.NewTable("information_schema", "column_domain_usage", DomainCatalogColumn, DomainSchemaColumn, DomainNameColumn, TableCatalogColumn, TableSchemaColumn, TableNameColumn, ColumnNameColumn),

		//Columns
		DomainCatalog: DomainCatalogColumn,
		DomainSchema:  DomainSchemaColumn,
		DomainName:    DomainNameColumn,
		TableCatalog:  TableCatalogColumn,
		TableSchema:   TableSchemaColumn,
		TableName:     TableNameColumn,
		ColumnName:    ColumnNameColumn,

		AllColumns:     postgres.ColumnList{DomainCatalogColumn, DomainSchemaColumn, DomainNameColumn, TableCatalogColumn, TableSchemaColumn, TableNameColumn, ColumnNameColumn},
		MutableColumns: postgres.ColumnList{DomainCatalogColumn, DomainSchemaColumn, DomainNameColumn, TableCatalogColumn, TableSchemaColumn, TableNameColumn, ColumnNameColumn},
	}
}
