//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var ForeignServerOptions = newForeignServerOptionsTable()

type ForeignServerOptionsTable struct {
	postgres.Table

	//Columns
	ForeignServerCatalog postgres.ColumnString
	ForeignServerName    postgres.ColumnString
	OptionName           postgres.ColumnString
	OptionValue          postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new ForeignServerOptionsTable with assigned alias
func (a *ForeignServerOptionsTable) AS(alias string) *ForeignServerOptionsTable {
	aliasTable := newForeignServerOptionsTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newForeignServerOptionsTable() *ForeignServerOptionsTable {
	var (
		ForeignServerCatalogColumn = postgres.StringColumn("foreign_server_catalog")
		ForeignServerNameColumn    = postgres.StringColumn("foreign_server_name")
		OptionNameColumn           = postgres.StringColumn("option_name")
		OptionValueColumn          = postgres.StringColumn("option_value")
	)

	return &ForeignServerOptionsTable{
		Table: postgres.NewTable("information_schema", "foreign_server_options", ForeignServerCatalogColumn, ForeignServerNameColumn, OptionNameColumn, OptionValueColumn),

		//Columns
		ForeignServerCatalog: ForeignServerCatalogColumn,
		ForeignServerName:    ForeignServerNameColumn,
		OptionName:           OptionNameColumn,
		OptionValue:          OptionValueColumn,

		AllColumns:     postgres.ColumnList{ForeignServerCatalogColumn, ForeignServerNameColumn, OptionNameColumn, OptionValueColumn},
		MutableColumns: postgres.ColumnList{ForeignServerCatalogColumn, ForeignServerNameColumn, OptionNameColumn, OptionValueColumn},
	}
}
