//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var RoleUsageGrants = newRoleUsageGrantsTable()

type RoleUsageGrantsTable struct {
	postgres.Table

	//Columns
	Grantor       postgres.ColumnString
	Grantee       postgres.ColumnString
	ObjectCatalog postgres.ColumnString
	ObjectSchema  postgres.ColumnString
	ObjectName    postgres.ColumnString
	ObjectType    postgres.ColumnString
	PrivilegeType postgres.ColumnString
	IsGrantable   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new RoleUsageGrantsTable with assigned alias
func (a *RoleUsageGrantsTable) AS(alias string) *RoleUsageGrantsTable {
	aliasTable := newRoleUsageGrantsTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newRoleUsageGrantsTable() *RoleUsageGrantsTable {
	var (
		GrantorColumn       = postgres.StringColumn("grantor")
		GranteeColumn       = postgres.StringColumn("grantee")
		ObjectCatalogColumn = postgres.StringColumn("object_catalog")
		ObjectSchemaColumn  = postgres.StringColumn("object_schema")
		ObjectNameColumn    = postgres.StringColumn("object_name")
		ObjectTypeColumn    = postgres.StringColumn("object_type")
		PrivilegeTypeColumn = postgres.StringColumn("privilege_type")
		IsGrantableColumn   = postgres.StringColumn("is_grantable")
	)

	return &RoleUsageGrantsTable{
		Table: postgres.NewTable("information_schema", "role_usage_grants", GrantorColumn, GranteeColumn, ObjectCatalogColumn, ObjectSchemaColumn, ObjectNameColumn, ObjectTypeColumn, PrivilegeTypeColumn, IsGrantableColumn),

		//Columns
		Grantor:       GrantorColumn,
		Grantee:       GranteeColumn,
		ObjectCatalog: ObjectCatalogColumn,
		ObjectSchema:  ObjectSchemaColumn,
		ObjectName:    ObjectNameColumn,
		ObjectType:    ObjectTypeColumn,
		PrivilegeType: PrivilegeTypeColumn,
		IsGrantable:   IsGrantableColumn,

		AllColumns:     postgres.ColumnList{GrantorColumn, GranteeColumn, ObjectCatalogColumn, ObjectSchemaColumn, ObjectNameColumn, ObjectTypeColumn, PrivilegeTypeColumn, IsGrantableColumn},
		MutableColumns: postgres.ColumnList{GrantorColumn, GranteeColumn, ObjectCatalogColumn, ObjectSchemaColumn, ObjectNameColumn, ObjectTypeColumn, PrivilegeTypeColumn, IsGrantableColumn},
	}
}
