//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var RoleUdtGrants = newRoleUdtGrantsTable()

type RoleUdtGrantsTable struct {
	postgres.Table

	//Columns
	Grantor       postgres.ColumnString
	Grantee       postgres.ColumnString
	UdtCatalog    postgres.ColumnString
	UdtSchema     postgres.ColumnString
	UdtName       postgres.ColumnString
	PrivilegeType postgres.ColumnString
	IsGrantable   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new RoleUdtGrantsTable with assigned alias
func (a *RoleUdtGrantsTable) AS(alias string) *RoleUdtGrantsTable {
	aliasTable := newRoleUdtGrantsTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newRoleUdtGrantsTable() *RoleUdtGrantsTable {
	var (
		GrantorColumn       = postgres.StringColumn("grantor")
		GranteeColumn       = postgres.StringColumn("grantee")
		UdtCatalogColumn    = postgres.StringColumn("udt_catalog")
		UdtSchemaColumn     = postgres.StringColumn("udt_schema")
		UdtNameColumn       = postgres.StringColumn("udt_name")
		PrivilegeTypeColumn = postgres.StringColumn("privilege_type")
		IsGrantableColumn   = postgres.StringColumn("is_grantable")
	)

	return &RoleUdtGrantsTable{
		Table: postgres.NewTable("information_schema", "role_udt_grants", GrantorColumn, GranteeColumn, UdtCatalogColumn, UdtSchemaColumn, UdtNameColumn, PrivilegeTypeColumn, IsGrantableColumn),

		//Columns
		Grantor:       GrantorColumn,
		Grantee:       GranteeColumn,
		UdtCatalog:    UdtCatalogColumn,
		UdtSchema:     UdtSchemaColumn,
		UdtName:       UdtNameColumn,
		PrivilegeType: PrivilegeTypeColumn,
		IsGrantable:   IsGrantableColumn,

		AllColumns:     postgres.ColumnList{GrantorColumn, GranteeColumn, UdtCatalogColumn, UdtSchemaColumn, UdtNameColumn, PrivilegeTypeColumn, IsGrantableColumn},
		MutableColumns: postgres.ColumnList{GrantorColumn, GranteeColumn, UdtCatalogColumn, UdtSchemaColumn, UdtNameColumn, PrivilegeTypeColumn, IsGrantableColumn},
	}
}
