//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var Schemata = newSchemataTable()

type SchemataTable struct {
	postgres.Table

	//Columns
	CatalogName                postgres.ColumnString
	SchemaName                 postgres.ColumnString
	SchemaOwner                postgres.ColumnString
	DefaultCharacterSetCatalog postgres.ColumnString
	DefaultCharacterSetSchema  postgres.ColumnString
	DefaultCharacterSetName    postgres.ColumnString
	SQLPath                    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new SchemataTable with assigned alias
func (a *SchemataTable) AS(alias string) *SchemataTable {
	aliasTable := newSchemataTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newSchemataTable() *SchemataTable {
	var (
		CatalogNameColumn                = postgres.StringColumn("catalog_name")
		SchemaNameColumn                 = postgres.StringColumn("schema_name")
		SchemaOwnerColumn                = postgres.StringColumn("schema_owner")
		DefaultCharacterSetCatalogColumn = postgres.StringColumn("default_character_set_catalog")
		DefaultCharacterSetSchemaColumn  = postgres.StringColumn("default_character_set_schema")
		DefaultCharacterSetNameColumn    = postgres.StringColumn("default_character_set_name")
		SQLPathColumn                    = postgres.StringColumn("sql_path")
	)

	return &SchemataTable{
		Table: postgres.NewTable("information_schema", "schemata", CatalogNameColumn, SchemaNameColumn, SchemaOwnerColumn, DefaultCharacterSetCatalogColumn, DefaultCharacterSetSchemaColumn, DefaultCharacterSetNameColumn, SQLPathColumn),

		//Columns
		CatalogName:                CatalogNameColumn,
		SchemaName:                 SchemaNameColumn,
		SchemaOwner:                SchemaOwnerColumn,
		DefaultCharacterSetCatalog: DefaultCharacterSetCatalogColumn,
		DefaultCharacterSetSchema:  DefaultCharacterSetSchemaColumn,
		DefaultCharacterSetName:    DefaultCharacterSetNameColumn,
		SQLPath:                    SQLPathColumn,

		AllColumns:     postgres.ColumnList{CatalogNameColumn, SchemaNameColumn, SchemaOwnerColumn, DefaultCharacterSetCatalogColumn, DefaultCharacterSetSchemaColumn, DefaultCharacterSetNameColumn, SQLPathColumn},
		MutableColumns: postgres.ColumnList{CatalogNameColumn, SchemaNameColumn, SchemaOwnerColumn, DefaultCharacterSetCatalogColumn, DefaultCharacterSetSchemaColumn, DefaultCharacterSetNameColumn, SQLPathColumn},
	}
}
