//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/postgres"
)

var ViewRoutineUsage = newViewRoutineUsageTable()

type ViewRoutineUsageTable struct {
	postgres.Table

	//Columns
	TableCatalog    postgres.ColumnString
	TableSchema     postgres.ColumnString
	TableName       postgres.ColumnString
	SpecificCatalog postgres.ColumnString
	SpecificSchema  postgres.ColumnString
	SpecificName    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new ViewRoutineUsageTable with assigned alias
func (a *ViewRoutineUsageTable) AS(alias string) *ViewRoutineUsageTable {
	aliasTable := newViewRoutineUsageTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newViewRoutineUsageTable() *ViewRoutineUsageTable {
	var (
		TableCatalogColumn    = postgres.StringColumn("table_catalog")
		TableSchemaColumn     = postgres.StringColumn("table_schema")
		TableNameColumn       = postgres.StringColumn("table_name")
		SpecificCatalogColumn = postgres.StringColumn("specific_catalog")
		SpecificSchemaColumn  = postgres.StringColumn("specific_schema")
		SpecificNameColumn    = postgres.StringColumn("specific_name")
	)

	return &ViewRoutineUsageTable{
		Table: postgres.NewTable("information_schema", "view_routine_usage", TableCatalogColumn, TableSchemaColumn, TableNameColumn, SpecificCatalogColumn, SpecificSchemaColumn, SpecificNameColumn),

		//Columns
		TableCatalog:    TableCatalogColumn,
		TableSchema:     TableSchemaColumn,
		TableName:       TableNameColumn,
		SpecificCatalog: SpecificCatalogColumn,
		SpecificSchema:  SpecificSchemaColumn,
		SpecificName:    SpecificNameColumn,

		AllColumns:     postgres.ColumnList{TableCatalogColumn, TableSchemaColumn, TableNameColumn, SpecificCatalogColumn, SpecificSchemaColumn, SpecificNameColumn},
		MutableColumns: postgres.ColumnList{TableCatalogColumn, TableSchemaColumn, TableNameColumn, SpecificCatalogColumn, SpecificSchemaColumn, SpecificNameColumn},
	}
}
