//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgAmop struct {
	Oid            string
	Amopfamily     string
	Amoplefttype   string
	Amoprighttype  string
	Amopstrategy   int16
	Amoppurpose    string
	Amopopr        string
	Amopmethod     string
	Amopsortfamily string
}
