//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgAttribute struct {
	Attrelid      string
	Attname       string
	Atttypid      string
	Attstattarget int32
	Attlen        int16
	Attnum        int16
	Attndims      int32
	Attcacheoff   int32
	Atttypmod     int32
	Attbyval      bool
	Attstorage    string
	Attalign      string
	Attnotnull    bool
	Atthasdef     bool
	Atthasmissing bool
	Attidentity   string
	Attgenerated  string
	Attisdropped  bool
	Attislocal    bool
	Attinhcount   int32
	Attcollation  string
	Attacl        *string
	Attoptions    *string
	Attfdwoptions *string
	Attmissingval *string
}
