//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgAm struct {
	Oid       string
	Amname    string
	Amhandler string
	Amtype    string
}
