//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgCollation struct {
	Oid                 string
	Collname            string
	Collnamespace       string
	Collowner           string
	Collprovider        string
	Collisdeterministic bool
	Collencoding        int32
	Collcollate         string
	Collctype           string
	Collversion         *string
}
