//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgCast struct {
	Oid         string
	Castsource  string
	Casttarget  string
	Castfunc    string
	Castcontext string
	Castmethod  string
}
