//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgConversion struct {
	Oid            string
	Conname        string
	Connamespace   string
	Conowner       string
	Conforencoding int32
	Contoencoding  int32
	Conproc        string
	Condefault     bool
}
