//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgExtension struct {
	Oid            string
	Extname        string
	Extowner       string
	Extnamespace   string
	Extrelocatable bool
	Extversion     string
	Extconfig      *string
	Extcondition   *string
}
