//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgForeignServer struct {
	Oid        string
	Srvname    string
	Srvowner   string
	Srvfdw     string
	Srvtype    *string
	Srvversion *string
	Srvacl     *string
	Srvoptions *string
}
