//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgMatviews struct {
	Schemaname   *string
	Matviewname  *string
	Matviewowner *string
	Tablespace   *string
	Hasindexes   *bool
	Ispopulated  *bool
	Definition   *string
}
