//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgOpclass struct {
	Oid          string
	Opcmethod    string
	Opcname      string
	Opcnamespace string
	Opcowner     string
	Opcfamily    string
	Opcintype    string
	Opcdefault   bool
	Opckeytype   string
}
