//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgPolicies struct {
	Schemaname *string
	Tablename  *string
	Policyname *string
	Permissive *string
	Roles      *string
	Cmd        *string
	Qual       *string
	WithCheck  *string
}
