//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgPublication struct {
	Oid          string
	Pubname      string
	Pubowner     string
	Puballtables bool
	Pubinsert    bool
	Pubupdate    bool
	Pubdelete    bool
	Pubtruncate  bool
	Pubviaroot   bool
}
