//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PgPreparedXacts struct {
	Transaction *string
	Gid         *string
	Prepared    *time.Time
	Owner       *string
	Database    *string
}
