//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatioSysSequences struct {
	Relid      *string
	Schemaname *string
	Relname    *string
	BlksRead   *int64
	BlksHit    *int64
}
