//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatGssapi struct {
	Pid              *int32
	GssAuthenticated *bool
	Principal        *string
	Encrypted        *bool
}
