//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatXactUserFunctions struct {
	Funcid     *string
	Schemaname *string
	Funcname   *string
	Calls      *int64
	TotalTime  *float64
	SelfTime   *float64
}
