//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgSettings struct {
	Name           *string
	Setting        *string
	Unit           *string
	Category       *string
	ShortDesc      *string
	ExtraDesc      *string
	Context        *string
	Vartype        *string
	Source         *string
	MinVal         *string
	MaxVal         *string
	Enumvals       *string
	BootVal        *string
	ResetVal       *string
	Sourcefile     *string
	Sourceline     *int32
	PendingRestart *bool
}
