//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatSsl struct {
	Pid          *int32
	Ssl          *bool
	Version      *string
	Cipher       *string
	Bits         *int32
	Compression  *bool
	ClientDn     *string
	ClientSerial *float64
	IssuerDn     *string
}
