//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgShdepend struct {
	Dbid       string
	Classid    string
	Objid      string
	Objsubid   int32
	Refclassid string
	Refobjid   string
	Deptype    string
}
