//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgSeclabel struct {
	Objoid   string
	Classoid string
	Objsubid int32
	Provider string
	Label    string
}
