//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStats struct {
	Schemaname          *string
	Tablename           *string
	Attname             *string
	Inherited           *bool
	NullFrac            *float32
	AvgWidth            *int32
	NDistinct           *float32
	MostCommonVals      *string
	MostCommonFreqs     *string
	HistogramBounds     *string
	Correlation         *float32
	MostCommonElems     *string
	MostCommonElemFreqs *string
	ElemCountHistogram  *string
}
