//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatDatabaseConflicts struct {
	Datid           *string
	Datname         *string
	ConflTablespace *int64
	ConflLock       *int64
	ConflSnapshot   *int64
	ConflBufferpin  *int64
	ConflDeadlock   *int64
}
