//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatProgressVacuum struct {
	Pid              *int32
	Datid            *string
	Datname          *string
	Relid            *string
	Phase            *string
	HeapBlksTotal    *int64
	HeapBlksScanned  *int64
	HeapBlksVacuumed *int64
	IndexVacuumCount *int64
	MaxDeadTuples    *int64
	NumDeadTuples    *int64
}
