//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgTsParser struct {
	Oid          string
	Prsname      string
	Prsnamespace string
	Prsstart     string
	Prstoken     string
	Prsend       string
	Prsheadline  string
	Prslextype   string
}
