//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgTables struct {
	Schemaname  *string
	Tablename   *string
	Tableowner  *string
	Tablespace  *string
	Hasindexes  *bool
	Hasrules    *bool
	Hastriggers *bool
	Rowsecurity *bool
}
