//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgType struct {
	Oid            string
	Typname        string
	Typnamespace   string
	Typowner       string
	Typlen         int16
	Typbyval       bool
	Typtype        string
	Typcategory    string
	Typispreferred bool
	Typisdefined   bool
	Typdelim       string
	Typrelid       string
	Typelem        string
	Typarray       string
	Typinput       string
	Typoutput      string
	Typreceive     string
	Typsend        string
	Typmodin       string
	Typmodout      string
	Typanalyze     string
	Typalign       string
	Typstorage     string
	Typnotnull     bool
	Typbasetype    string
	Typtypmod      int32
	Typndims       int32
	Typcollation   string
	Typdefaultbin  *string
	Typdefault     *string
	Typacl         *string
}
