//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PgUser struct {
	Usename      *string
	Usesysid     *string
	Usecreatedb  *bool
	Usesuper     *bool
	Userepl      *bool
	Usebypassrls *bool
	Passwd       *string
	Valuntil     *time.Time
	Useconfig    *string
}
