//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgAttrdef = newPgAttrdefTable()

type pgAttrdefTable struct {
	postgres.Table

	//Columns
	Oid     postgres.ColumnString
	Adrelid postgres.ColumnString
	Adnum   postgres.ColumnInteger
	Adbin   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgAttrdefTable struct {
	pgAttrdefTable

	EXCLUDED pgAttrdefTable
}

// AS creates new PgAttrdefTable with assigned alias
func (a *PgAttrdefTable) AS(alias string) *PgAttrdefTable {
	aliasTable := newPgAttrdefTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgAttrdefTable() *PgAttrdefTable {
	return &PgAttrdefTable{
		pgAttrdefTable: newPgAttrdefTableImpl("pg_catalog", "pg_attrdef"),
		EXCLUDED:       newPgAttrdefTableImpl("", "excluded"),
	}
}

func newPgAttrdefTableImpl(schemaName, tableName string) pgAttrdefTable {
	var (
		OidColumn      = postgres.StringColumn("oid")
		AdrelidColumn  = postgres.StringColumn("adrelid")
		AdnumColumn    = postgres.IntegerColumn("adnum")
		AdbinColumn    = postgres.StringColumn("adbin")
		allColumns     = postgres.ColumnList{OidColumn, AdrelidColumn, AdnumColumn, AdbinColumn}
		mutableColumns = postgres.ColumnList{OidColumn, AdrelidColumn, AdnumColumn, AdbinColumn}
	)

	return pgAttrdefTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Oid:     OidColumn,
		Adrelid: AdrelidColumn,
		Adnum:   AdnumColumn,
		Adbin:   AdbinColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
