//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgAmop = newPgAmopTable()

type pgAmopTable struct {
	postgres.Table

	//Columns
	Oid            postgres.ColumnString
	Amopfamily     postgres.ColumnString
	Amoplefttype   postgres.ColumnString
	Amoprighttype  postgres.ColumnString
	Amopstrategy   postgres.ColumnInteger
	Amoppurpose    postgres.ColumnString
	Amopopr        postgres.ColumnString
	Amopmethod     postgres.ColumnString
	Amopsortfamily postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgAmopTable struct {
	pgAmopTable

	EXCLUDED pgAmopTable
}

// AS creates new PgAmopTable with assigned alias
func (a *PgAmopTable) AS(alias string) *PgAmopTable {
	aliasTable := newPgAmopTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgAmopTable() *PgAmopTable {
	return &PgAmopTable{
		pgAmopTable: newPgAmopTableImpl("pg_catalog", "pg_amop"),
		EXCLUDED:    newPgAmopTableImpl("", "excluded"),
	}
}

func newPgAmopTableImpl(schemaName, tableName string) pgAmopTable {
	var (
		OidColumn            = postgres.StringColumn("oid")
		AmopfamilyColumn     = postgres.StringColumn("amopfamily")
		AmoplefttypeColumn   = postgres.StringColumn("amoplefttype")
		AmoprighttypeColumn  = postgres.StringColumn("amoprighttype")
		AmopstrategyColumn   = postgres.IntegerColumn("amopstrategy")
		AmoppurposeColumn    = postgres.StringColumn("amoppurpose")
		AmopoprColumn        = postgres.StringColumn("amopopr")
		AmopmethodColumn     = postgres.StringColumn("amopmethod")
		AmopsortfamilyColumn = postgres.StringColumn("amopsortfamily")
		allColumns           = postgres.ColumnList{OidColumn, AmopfamilyColumn, AmoplefttypeColumn, AmoprighttypeColumn, AmopstrategyColumn, AmoppurposeColumn, AmopoprColumn, AmopmethodColumn, AmopsortfamilyColumn}
		mutableColumns       = postgres.ColumnList{OidColumn, AmopfamilyColumn, AmoplefttypeColumn, AmoprighttypeColumn, AmopstrategyColumn, AmoppurposeColumn, AmopoprColumn, AmopmethodColumn, AmopsortfamilyColumn}
	)

	return pgAmopTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Oid:            OidColumn,
		Amopfamily:     AmopfamilyColumn,
		Amoplefttype:   AmoplefttypeColumn,
		Amoprighttype:  AmoprighttypeColumn,
		Amopstrategy:   AmopstrategyColumn,
		Amoppurpose:    AmoppurposeColumn,
		Amopopr:        AmopoprColumn,
		Amopmethod:     AmopmethodColumn,
		Amopsortfamily: AmopsortfamilyColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
