//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgCast = newPgCastTable()

type PgCastTable struct {
	postgres.Table

	//Columns
	Oid         postgres.ColumnString
	Castsource  postgres.ColumnString
	Casttarget  postgres.ColumnString
	Castfunc    postgres.ColumnString
	Castcontext postgres.ColumnString
	Castmethod  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgCastTable with assigned alias
func (a *PgCastTable) AS(alias string) *PgCastTable {
	aliasTable := newPgCastTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgCastTable() *PgCastTable {
	var (
		OidColumn         = postgres.StringColumn("oid")
		CastsourceColumn  = postgres.StringColumn("castsource")
		CasttargetColumn  = postgres.StringColumn("casttarget")
		CastfuncColumn    = postgres.StringColumn("castfunc")
		CastcontextColumn = postgres.StringColumn("castcontext")
		CastmethodColumn  = postgres.StringColumn("castmethod")
	)

	return &PgCastTable{
		Table: postgres.NewTable("pg_catalog", "pg_cast", OidColumn, CastsourceColumn, CasttargetColumn, CastfuncColumn, CastcontextColumn, CastmethodColumn),

		//Columns
		Oid:         OidColumn,
		Castsource:  CastsourceColumn,
		Casttarget:  CasttargetColumn,
		Castfunc:    CastfuncColumn,
		Castcontext: CastcontextColumn,
		Castmethod:  CastmethodColumn,

		AllColumns:     postgres.ColumnList{OidColumn, CastsourceColumn, CasttargetColumn, CastfuncColumn, CastcontextColumn, CastmethodColumn},
		MutableColumns: postgres.ColumnList{OidColumn, CastsourceColumn, CasttargetColumn, CastfuncColumn, CastcontextColumn, CastmethodColumn},
	}
}
