//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgDatabase = newPgDatabaseTable()

type PgDatabaseTable struct {
	postgres.Table

	//Columns
	Oid           postgres.ColumnString
	Datname       postgres.ColumnString
	Datdba        postgres.ColumnString
	Encoding      postgres.ColumnInteger
	Datcollate    postgres.ColumnString
	Datctype      postgres.ColumnString
	Datistemplate postgres.ColumnBool
	Datallowconn  postgres.ColumnBool
	Datconnlimit  postgres.ColumnInteger
	Datlastsysoid postgres.ColumnString
	Datfrozenxid  postgres.ColumnString
	Datminmxid    postgres.ColumnString
	Dattablespace postgres.ColumnString
	Datacl        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgDatabaseTable with assigned alias
func (a *PgDatabaseTable) AS(alias string) *PgDatabaseTable {
	aliasTable := newPgDatabaseTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgDatabaseTable() *PgDatabaseTable {
	var (
		OidColumn           = postgres.StringColumn("oid")
		DatnameColumn       = postgres.StringColumn("datname")
		DatdbaColumn        = postgres.StringColumn("datdba")
		EncodingColumn      = postgres.IntegerColumn("encoding")
		DatcollateColumn    = postgres.StringColumn("datcollate")
		DatctypeColumn      = postgres.StringColumn("datctype")
		DatistemplateColumn = postgres.BoolColumn("datistemplate")
		DatallowconnColumn  = postgres.BoolColumn("datallowconn")
		DatconnlimitColumn  = postgres.IntegerColumn("datconnlimit")
		DatlastsysoidColumn = postgres.StringColumn("datlastsysoid")
		DatfrozenxidColumn  = postgres.StringColumn("datfrozenxid")
		DatminmxidColumn    = postgres.StringColumn("datminmxid")
		DattablespaceColumn = postgres.StringColumn("dattablespace")
		DataclColumn        = postgres.StringColumn("datacl")
	)

	return &PgDatabaseTable{
		Table: postgres.NewTable("pg_catalog", "pg_database", OidColumn, DatnameColumn, DatdbaColumn, EncodingColumn, DatcollateColumn, DatctypeColumn, DatistemplateColumn, DatallowconnColumn, DatconnlimitColumn, DatlastsysoidColumn, DatfrozenxidColumn, DatminmxidColumn, DattablespaceColumn, DataclColumn),

		//Columns
		Oid:           OidColumn,
		Datname:       DatnameColumn,
		Datdba:        DatdbaColumn,
		Encoding:      EncodingColumn,
		Datcollate:    DatcollateColumn,
		Datctype:      DatctypeColumn,
		Datistemplate: DatistemplateColumn,
		Datallowconn:  DatallowconnColumn,
		Datconnlimit:  DatconnlimitColumn,
		Datlastsysoid: DatlastsysoidColumn,
		Datfrozenxid:  DatfrozenxidColumn,
		Datminmxid:    DatminmxidColumn,
		Dattablespace: DattablespaceColumn,
		Datacl:        DataclColumn,

		AllColumns:     postgres.ColumnList{OidColumn, DatnameColumn, DatdbaColumn, EncodingColumn, DatcollateColumn, DatctypeColumn, DatistemplateColumn, DatallowconnColumn, DatconnlimitColumn, DatlastsysoidColumn, DatfrozenxidColumn, DatminmxidColumn, DattablespaceColumn, DataclColumn},
		MutableColumns: postgres.ColumnList{OidColumn, DatnameColumn, DatdbaColumn, EncodingColumn, DatcollateColumn, DatctypeColumn, DatistemplateColumn, DatallowconnColumn, DatconnlimitColumn, DatlastsysoidColumn, DatfrozenxidColumn, DatminmxidColumn, DattablespaceColumn, DataclColumn},
	}
}
