//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgDescription = newPgDescriptionTable()

type PgDescriptionTable struct {
	postgres.Table

	//Columns
	Objoid      postgres.ColumnString
	Classoid    postgres.ColumnString
	Objsubid    postgres.ColumnInteger
	Description postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgDescriptionTable with assigned alias
func (a *PgDescriptionTable) AS(alias string) *PgDescriptionTable {
	aliasTable := newPgDescriptionTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgDescriptionTable() *PgDescriptionTable {
	var (
		ObjoidColumn      = postgres.StringColumn("objoid")
		ClassoidColumn    = postgres.StringColumn("classoid")
		ObjsubidColumn    = postgres.IntegerColumn("objsubid")
		DescriptionColumn = postgres.StringColumn("description")
	)

	return &PgDescriptionTable{
		Table: postgres.NewTable("pg_catalog", "pg_description", ObjoidColumn, ClassoidColumn, ObjsubidColumn, DescriptionColumn),

		//Columns
		Objoid:      ObjoidColumn,
		Classoid:    ClassoidColumn,
		Objsubid:    ObjsubidColumn,
		Description: DescriptionColumn,

		AllColumns:     postgres.ColumnList{ObjoidColumn, ClassoidColumn, ObjsubidColumn, DescriptionColumn},
		MutableColumns: postgres.ColumnList{ObjoidColumn, ClassoidColumn, ObjsubidColumn, DescriptionColumn},
	}
}
