//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgEventTrigger = newPgEventTriggerTable()

type PgEventTriggerTable struct {
	postgres.Table

	//Columns
	Oid        postgres.ColumnString
	Evtname    postgres.ColumnString
	Evtevent   postgres.ColumnString
	Evtowner   postgres.ColumnString
	Evtfoid    postgres.ColumnString
	Evtenabled postgres.ColumnString
	Evttags    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgEventTriggerTable with assigned alias
func (a *PgEventTriggerTable) AS(alias string) *PgEventTriggerTable {
	aliasTable := newPgEventTriggerTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgEventTriggerTable() *PgEventTriggerTable {
	var (
		OidColumn        = postgres.StringColumn("oid")
		EvtnameColumn    = postgres.StringColumn("evtname")
		EvteventColumn   = postgres.StringColumn("evtevent")
		EvtownerColumn   = postgres.StringColumn("evtowner")
		EvtfoidColumn    = postgres.StringColumn("evtfoid")
		EvtenabledColumn = postgres.StringColumn("evtenabled")
		EvttagsColumn    = postgres.StringColumn("evttags")
	)

	return &PgEventTriggerTable{
		Table: postgres.NewTable("pg_catalog", "pg_event_trigger", OidColumn, EvtnameColumn, EvteventColumn, EvtownerColumn, EvtfoidColumn, EvtenabledColumn, EvttagsColumn),

		//Columns
		Oid:        OidColumn,
		Evtname:    EvtnameColumn,
		Evtevent:   EvteventColumn,
		Evtowner:   EvtownerColumn,
		Evtfoid:    EvtfoidColumn,
		Evtenabled: EvtenabledColumn,
		Evttags:    EvttagsColumn,

		AllColumns:     postgres.ColumnList{OidColumn, EvtnameColumn, EvteventColumn, EvtownerColumn, EvtfoidColumn, EvtenabledColumn, EvttagsColumn},
		MutableColumns: postgres.ColumnList{OidColumn, EvtnameColumn, EvteventColumn, EvtownerColumn, EvtfoidColumn, EvtenabledColumn, EvttagsColumn},
	}
}
