//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgExtension = newPgExtensionTable()

type PgExtensionTable struct {
	postgres.Table

	//Columns
	Oid            postgres.ColumnString
	Extname        postgres.ColumnString
	Extowner       postgres.ColumnString
	Extnamespace   postgres.ColumnString
	Extrelocatable postgres.ColumnBool
	Extversion     postgres.ColumnString
	Extconfig      postgres.ColumnString
	Extcondition   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgExtensionTable with assigned alias
func (a *PgExtensionTable) AS(alias string) *PgExtensionTable {
	aliasTable := newPgExtensionTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgExtensionTable() *PgExtensionTable {
	var (
		OidColumn            = postgres.StringColumn("oid")
		ExtnameColumn        = postgres.StringColumn("extname")
		ExtownerColumn       = postgres.StringColumn("extowner")
		ExtnamespaceColumn   = postgres.StringColumn("extnamespace")
		ExtrelocatableColumn = postgres.BoolColumn("extrelocatable")
		ExtversionColumn     = postgres.StringColumn("extversion")
		ExtconfigColumn      = postgres.StringColumn("extconfig")
		ExtconditionColumn   = postgres.StringColumn("extcondition")
	)

	return &PgExtensionTable{
		Table: postgres.NewTable("pg_catalog", "pg_extension", OidColumn, ExtnameColumn, ExtownerColumn, ExtnamespaceColumn, ExtrelocatableColumn, ExtversionColumn, ExtconfigColumn, ExtconditionColumn),

		//Columns
		Oid:            OidColumn,
		Extname:        ExtnameColumn,
		Extowner:       ExtownerColumn,
		Extnamespace:   ExtnamespaceColumn,
		Extrelocatable: ExtrelocatableColumn,
		Extversion:     ExtversionColumn,
		Extconfig:      ExtconfigColumn,
		Extcondition:   ExtconditionColumn,

		AllColumns:     postgres.ColumnList{OidColumn, ExtnameColumn, ExtownerColumn, ExtnamespaceColumn, ExtrelocatableColumn, ExtversionColumn, ExtconfigColumn, ExtconditionColumn},
		MutableColumns: postgres.ColumnList{OidColumn, ExtnameColumn, ExtownerColumn, ExtnamespaceColumn, ExtrelocatableColumn, ExtversionColumn, ExtconfigColumn, ExtconditionColumn},
	}
}
