//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgForeignServer = newPgForeignServerTable()

type pgForeignServerTable struct {
	postgres.Table

	//Columns
	Oid        postgres.ColumnString
	Srvname    postgres.ColumnString
	Srvowner   postgres.ColumnString
	Srvfdw     postgres.ColumnString
	Srvtype    postgres.ColumnString
	Srvversion postgres.ColumnString
	Srvacl     postgres.ColumnString
	Srvoptions postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgForeignServerTable struct {
	pgForeignServerTable

	EXCLUDED pgForeignServerTable
}

// AS creates new PgForeignServerTable with assigned alias
func (a *PgForeignServerTable) AS(alias string) *PgForeignServerTable {
	aliasTable := newPgForeignServerTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgForeignServerTable() *PgForeignServerTable {
	return &PgForeignServerTable{
		pgForeignServerTable: newPgForeignServerTableImpl("pg_catalog", "pg_foreign_server"),
		EXCLUDED:             newPgForeignServerTableImpl("", "excluded"),
	}
}

func newPgForeignServerTableImpl(schemaName, tableName string) pgForeignServerTable {
	var (
		OidColumn        = postgres.StringColumn("oid")
		SrvnameColumn    = postgres.StringColumn("srvname")
		SrvownerColumn   = postgres.StringColumn("srvowner")
		SrvfdwColumn     = postgres.StringColumn("srvfdw")
		SrvtypeColumn    = postgres.StringColumn("srvtype")
		SrvversionColumn = postgres.StringColumn("srvversion")
		SrvaclColumn     = postgres.StringColumn("srvacl")
		SrvoptionsColumn = postgres.StringColumn("srvoptions")
		allColumns       = postgres.ColumnList{OidColumn, SrvnameColumn, SrvownerColumn, SrvfdwColumn, SrvtypeColumn, SrvversionColumn, SrvaclColumn, SrvoptionsColumn}
		mutableColumns   = postgres.ColumnList{OidColumn, SrvnameColumn, SrvownerColumn, SrvfdwColumn, SrvtypeColumn, SrvversionColumn, SrvaclColumn, SrvoptionsColumn}
	)

	return pgForeignServerTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Oid:        OidColumn,
		Srvname:    SrvnameColumn,
		Srvowner:   SrvownerColumn,
		Srvfdw:     SrvfdwColumn,
		Srvtype:    SrvtypeColumn,
		Srvversion: SrvversionColumn,
		Srvacl:     SrvaclColumn,
		Srvoptions: SrvoptionsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
