//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgForeignServer = newPgForeignServerTable()

type PgForeignServerTable struct {
	postgres.Table

	//Columns
	Oid        postgres.ColumnString
	Srvname    postgres.ColumnString
	Srvowner   postgres.ColumnString
	Srvfdw     postgres.ColumnString
	Srvtype    postgres.ColumnString
	Srvversion postgres.ColumnString
	Srvacl     postgres.ColumnString
	Srvoptions postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgForeignServerTable with assigned alias
func (a *PgForeignServerTable) AS(alias string) *PgForeignServerTable {
	aliasTable := newPgForeignServerTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgForeignServerTable() *PgForeignServerTable {
	var (
		OidColumn        = postgres.StringColumn("oid")
		SrvnameColumn    = postgres.StringColumn("srvname")
		SrvownerColumn   = postgres.StringColumn("srvowner")
		SrvfdwColumn     = postgres.StringColumn("srvfdw")
		SrvtypeColumn    = postgres.StringColumn("srvtype")
		SrvversionColumn = postgres.StringColumn("srvversion")
		SrvaclColumn     = postgres.StringColumn("srvacl")
		SrvoptionsColumn = postgres.StringColumn("srvoptions")
	)

	return &PgForeignServerTable{
		Table: postgres.NewTable("pg_catalog", "pg_foreign_server", OidColumn, SrvnameColumn, SrvownerColumn, SrvfdwColumn, SrvtypeColumn, SrvversionColumn, SrvaclColumn, SrvoptionsColumn),

		//Columns
		Oid:        OidColumn,
		Srvname:    SrvnameColumn,
		Srvowner:   SrvownerColumn,
		Srvfdw:     SrvfdwColumn,
		Srvtype:    SrvtypeColumn,
		Srvversion: SrvversionColumn,
		Srvacl:     SrvaclColumn,
		Srvoptions: SrvoptionsColumn,

		AllColumns:     postgres.ColumnList{OidColumn, SrvnameColumn, SrvownerColumn, SrvfdwColumn, SrvtypeColumn, SrvversionColumn, SrvaclColumn, SrvoptionsColumn},
		MutableColumns: postgres.ColumnList{OidColumn, SrvnameColumn, SrvownerColumn, SrvfdwColumn, SrvtypeColumn, SrvversionColumn, SrvaclColumn, SrvoptionsColumn},
	}
}
