//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgInherits = newPgInheritsTable()

type pgInheritsTable struct {
	postgres.Table

	//Columns
	Inhrelid  postgres.ColumnString
	Inhparent postgres.ColumnString
	Inhseqno  postgres.ColumnInteger

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgInheritsTable struct {
	pgInheritsTable

	EXCLUDED pgInheritsTable
}

// AS creates new PgInheritsTable with assigned alias
func (a *PgInheritsTable) AS(alias string) *PgInheritsTable {
	aliasTable := newPgInheritsTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgInheritsTable() *PgInheritsTable {
	return &PgInheritsTable{
		pgInheritsTable: newPgInheritsTableImpl("pg_catalog", "pg_inherits"),
		EXCLUDED:        newPgInheritsTableImpl("", "excluded"),
	}
}

func newPgInheritsTableImpl(schemaName, tableName string) pgInheritsTable {
	var (
		InhrelidColumn  = postgres.StringColumn("inhrelid")
		InhparentColumn = postgres.StringColumn("inhparent")
		InhseqnoColumn  = postgres.IntegerColumn("inhseqno")
		allColumns      = postgres.ColumnList{InhrelidColumn, InhparentColumn, InhseqnoColumn}
		mutableColumns  = postgres.ColumnList{InhrelidColumn, InhparentColumn, InhseqnoColumn}
	)

	return pgInheritsTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Inhrelid:  InhrelidColumn,
		Inhparent: InhparentColumn,
		Inhseqno:  InhseqnoColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
