//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgLanguage = newPgLanguageTable()

type pgLanguageTable struct {
	postgres.Table

	//Columns
	Oid           postgres.ColumnString
	Lanname       postgres.ColumnString
	Lanowner      postgres.ColumnString
	Lanispl       postgres.ColumnBool
	Lanpltrusted  postgres.ColumnBool
	Lanplcallfoid postgres.ColumnString
	Laninline     postgres.ColumnString
	Lanvalidator  postgres.ColumnString
	Lanacl        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgLanguageTable struct {
	pgLanguageTable

	EXCLUDED pgLanguageTable
}

// AS creates new PgLanguageTable with assigned alias
func (a *PgLanguageTable) AS(alias string) *PgLanguageTable {
	aliasTable := newPgLanguageTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgLanguageTable() *PgLanguageTable {
	return &PgLanguageTable{
		pgLanguageTable: newPgLanguageTableImpl("pg_catalog", "pg_language"),
		EXCLUDED:        newPgLanguageTableImpl("", "excluded"),
	}
}

func newPgLanguageTableImpl(schemaName, tableName string) pgLanguageTable {
	var (
		OidColumn           = postgres.StringColumn("oid")
		LannameColumn       = postgres.StringColumn("lanname")
		LanownerColumn      = postgres.StringColumn("lanowner")
		LanisplColumn       = postgres.BoolColumn("lanispl")
		LanpltrustedColumn  = postgres.BoolColumn("lanpltrusted")
		LanplcallfoidColumn = postgres.StringColumn("lanplcallfoid")
		LaninlineColumn     = postgres.StringColumn("laninline")
		LanvalidatorColumn  = postgres.StringColumn("lanvalidator")
		LanaclColumn        = postgres.StringColumn("lanacl")
		allColumns          = postgres.ColumnList{OidColumn, LannameColumn, LanownerColumn, LanisplColumn, LanpltrustedColumn, LanplcallfoidColumn, LaninlineColumn, LanvalidatorColumn, LanaclColumn}
		mutableColumns      = postgres.ColumnList{OidColumn, LannameColumn, LanownerColumn, LanisplColumn, LanpltrustedColumn, LanplcallfoidColumn, LaninlineColumn, LanvalidatorColumn, LanaclColumn}
	)

	return pgLanguageTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Oid:           OidColumn,
		Lanname:       LannameColumn,
		Lanowner:      LanownerColumn,
		Lanispl:       LanisplColumn,
		Lanpltrusted:  LanpltrustedColumn,
		Lanplcallfoid: LanplcallfoidColumn,
		Laninline:     LaninlineColumn,
		Lanvalidator:  LanvalidatorColumn,
		Lanacl:        LanaclColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
