//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgOpclass = newPgOpclassTable()

type PgOpclassTable struct {
	postgres.Table

	//Columns
	Oid          postgres.ColumnString
	Opcmethod    postgres.ColumnString
	Opcname      postgres.ColumnString
	Opcnamespace postgres.ColumnString
	Opcowner     postgres.ColumnString
	Opcfamily    postgres.ColumnString
	Opcintype    postgres.ColumnString
	Opcdefault   postgres.ColumnBool
	Opckeytype   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgOpclassTable with assigned alias
func (a *PgOpclassTable) AS(alias string) *PgOpclassTable {
	aliasTable := newPgOpclassTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgOpclassTable() *PgOpclassTable {
	var (
		OidColumn          = postgres.StringColumn("oid")
		OpcmethodColumn    = postgres.StringColumn("opcmethod")
		OpcnameColumn      = postgres.StringColumn("opcname")
		OpcnamespaceColumn = postgres.StringColumn("opcnamespace")
		OpcownerColumn     = postgres.StringColumn("opcowner")
		OpcfamilyColumn    = postgres.StringColumn("opcfamily")
		OpcintypeColumn    = postgres.StringColumn("opcintype")
		OpcdefaultColumn   = postgres.BoolColumn("opcdefault")
		OpckeytypeColumn   = postgres.StringColumn("opckeytype")
	)

	return &PgOpclassTable{
		Table: postgres.NewTable("pg_catalog", "pg_opclass", OidColumn, OpcmethodColumn, OpcnameColumn, OpcnamespaceColumn, OpcownerColumn, OpcfamilyColumn, OpcintypeColumn, OpcdefaultColumn, OpckeytypeColumn),

		//Columns
		Oid:          OidColumn,
		Opcmethod:    OpcmethodColumn,
		Opcname:      OpcnameColumn,
		Opcnamespace: OpcnamespaceColumn,
		Opcowner:     OpcownerColumn,
		Opcfamily:    OpcfamilyColumn,
		Opcintype:    OpcintypeColumn,
		Opcdefault:   OpcdefaultColumn,
		Opckeytype:   OpckeytypeColumn,

		AllColumns:     postgres.ColumnList{OidColumn, OpcmethodColumn, OpcnameColumn, OpcnamespaceColumn, OpcownerColumn, OpcfamilyColumn, OpcintypeColumn, OpcdefaultColumn, OpckeytypeColumn},
		MutableColumns: postgres.ColumnList{OidColumn, OpcmethodColumn, OpcnameColumn, OpcnamespaceColumn, OpcownerColumn, OpcfamilyColumn, OpcintypeColumn, OpcdefaultColumn, OpckeytypeColumn},
	}
}
