//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgPublication = newPgPublicationTable()

type pgPublicationTable struct {
	postgres.Table

	//Columns
	Oid          postgres.ColumnString
	Pubname      postgres.ColumnString
	Pubowner     postgres.ColumnString
	Puballtables postgres.ColumnBool
	Pubinsert    postgres.ColumnBool
	Pubupdate    postgres.ColumnBool
	Pubdelete    postgres.ColumnBool
	Pubtruncate  postgres.ColumnBool
	Pubviaroot   postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgPublicationTable struct {
	pgPublicationTable

	EXCLUDED pgPublicationTable
}

// AS creates new PgPublicationTable with assigned alias
func (a *PgPublicationTable) AS(alias string) *PgPublicationTable {
	aliasTable := newPgPublicationTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgPublicationTable() *PgPublicationTable {
	return &PgPublicationTable{
		pgPublicationTable: newPgPublicationTableImpl("pg_catalog", "pg_publication"),
		EXCLUDED:           newPgPublicationTableImpl("", "excluded"),
	}
}

func newPgPublicationTableImpl(schemaName, tableName string) pgPublicationTable {
	var (
		OidColumn          = postgres.StringColumn("oid")
		PubnameColumn      = postgres.StringColumn("pubname")
		PubownerColumn     = postgres.StringColumn("pubowner")
		PuballtablesColumn = postgres.BoolColumn("puballtables")
		PubinsertColumn    = postgres.BoolColumn("pubinsert")
		PubupdateColumn    = postgres.BoolColumn("pubupdate")
		PubdeleteColumn    = postgres.BoolColumn("pubdelete")
		PubtruncateColumn  = postgres.BoolColumn("pubtruncate")
		PubviarootColumn   = postgres.BoolColumn("pubviaroot")
		allColumns         = postgres.ColumnList{OidColumn, PubnameColumn, PubownerColumn, PuballtablesColumn, PubinsertColumn, PubupdateColumn, PubdeleteColumn, PubtruncateColumn, PubviarootColumn}
		mutableColumns     = postgres.ColumnList{OidColumn, PubnameColumn, PubownerColumn, PuballtablesColumn, PubinsertColumn, PubupdateColumn, PubdeleteColumn, PubtruncateColumn, PubviarootColumn}
	)

	return pgPublicationTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Oid:          OidColumn,
		Pubname:      PubnameColumn,
		Pubowner:     PubownerColumn,
		Puballtables: PuballtablesColumn,
		Pubinsert:    PubinsertColumn,
		Pubupdate:    PubupdateColumn,
		Pubdelete:    PubdeleteColumn,
		Pubtruncate:  PubtruncateColumn,
		Pubviaroot:   PubviarootColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
