//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgPublicationRel = newPgPublicationRelTable()

type pgPublicationRelTable struct {
	postgres.Table

	//Columns
	Oid     postgres.ColumnString
	Prpubid postgres.ColumnString
	Prrelid postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgPublicationRelTable struct {
	pgPublicationRelTable

	EXCLUDED pgPublicationRelTable
}

// AS creates new PgPublicationRelTable with assigned alias
func (a *PgPublicationRelTable) AS(alias string) *PgPublicationRelTable {
	aliasTable := newPgPublicationRelTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgPublicationRelTable() *PgPublicationRelTable {
	return &PgPublicationRelTable{
		pgPublicationRelTable: newPgPublicationRelTableImpl("pg_catalog", "pg_publication_rel"),
		EXCLUDED:              newPgPublicationRelTableImpl("", "excluded"),
	}
}

func newPgPublicationRelTableImpl(schemaName, tableName string) pgPublicationRelTable {
	var (
		OidColumn      = postgres.StringColumn("oid")
		PrpubidColumn  = postgres.StringColumn("prpubid")
		PrrelidColumn  = postgres.StringColumn("prrelid")
		allColumns     = postgres.ColumnList{OidColumn, PrpubidColumn, PrrelidColumn}
		mutableColumns = postgres.ColumnList{OidColumn, PrpubidColumn, PrrelidColumn}
	)

	return pgPublicationRelTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Oid:     OidColumn,
		Prpubid: PrpubidColumn,
		Prrelid: PrrelidColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
