//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgPartitionedTable = newPgPartitionedTableTable()

type pgPartitionedTableTable struct {
	postgres.Table

	//Columns
	Partrelid     postgres.ColumnString
	Partstrat     postgres.ColumnString
	Partnatts     postgres.ColumnInteger
	Partdefid     postgres.ColumnString
	Partattrs     postgres.ColumnString
	Partclass     postgres.ColumnString
	Partcollation postgres.ColumnString
	Partexprs     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgPartitionedTableTable struct {
	pgPartitionedTableTable

	EXCLUDED pgPartitionedTableTable
}

// AS creates new PgPartitionedTableTable with assigned alias
func (a *PgPartitionedTableTable) AS(alias string) *PgPartitionedTableTable {
	aliasTable := newPgPartitionedTableTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgPartitionedTableTable() *PgPartitionedTableTable {
	return &PgPartitionedTableTable{
		pgPartitionedTableTable: newPgPartitionedTableTableImpl("pg_catalog", "pg_partitioned_table"),
		EXCLUDED:                newPgPartitionedTableTableImpl("", "excluded"),
	}
}

func newPgPartitionedTableTableImpl(schemaName, tableName string) pgPartitionedTableTable {
	var (
		PartrelidColumn     = postgres.StringColumn("partrelid")
		PartstratColumn     = postgres.StringColumn("partstrat")
		PartnattsColumn     = postgres.IntegerColumn("partnatts")
		PartdefidColumn     = postgres.StringColumn("partdefid")
		PartattrsColumn     = postgres.StringColumn("partattrs")
		PartclassColumn     = postgres.StringColumn("partclass")
		PartcollationColumn = postgres.StringColumn("partcollation")
		PartexprsColumn     = postgres.StringColumn("partexprs")
		allColumns          = postgres.ColumnList{PartrelidColumn, PartstratColumn, PartnattsColumn, PartdefidColumn, PartattrsColumn, PartclassColumn, PartcollationColumn, PartexprsColumn}
		mutableColumns      = postgres.ColumnList{PartrelidColumn, PartstratColumn, PartnattsColumn, PartdefidColumn, PartattrsColumn, PartclassColumn, PartcollationColumn, PartexprsColumn}
	)

	return pgPartitionedTableTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Partrelid:     PartrelidColumn,
		Partstrat:     PartstratColumn,
		Partnatts:     PartnattsColumn,
		Partdefid:     PartdefidColumn,
		Partattrs:     PartattrsColumn,
		Partclass:     PartclassColumn,
		Partcollation: PartcollationColumn,
		Partexprs:     PartexprsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
