//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgPolicy = newPgPolicyTable()

type pgPolicyTable struct {
	postgres.Table

	//Columns
	Oid           postgres.ColumnString
	Polname       postgres.ColumnString
	Polrelid      postgres.ColumnString
	Polcmd        postgres.ColumnString
	Polpermissive postgres.ColumnBool
	Polroles      postgres.ColumnString
	Polqual       postgres.ColumnString
	Polwithcheck  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgPolicyTable struct {
	pgPolicyTable

	EXCLUDED pgPolicyTable
}

// AS creates new PgPolicyTable with assigned alias
func (a *PgPolicyTable) AS(alias string) *PgPolicyTable {
	aliasTable := newPgPolicyTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgPolicyTable() *PgPolicyTable {
	return &PgPolicyTable{
		pgPolicyTable: newPgPolicyTableImpl("pg_catalog", "pg_policy"),
		EXCLUDED:      newPgPolicyTableImpl("", "excluded"),
	}
}

func newPgPolicyTableImpl(schemaName, tableName string) pgPolicyTable {
	var (
		OidColumn           = postgres.StringColumn("oid")
		PolnameColumn       = postgres.StringColumn("polname")
		PolrelidColumn      = postgres.StringColumn("polrelid")
		PolcmdColumn        = postgres.StringColumn("polcmd")
		PolpermissiveColumn = postgres.BoolColumn("polpermissive")
		PolrolesColumn      = postgres.StringColumn("polroles")
		PolqualColumn       = postgres.StringColumn("polqual")
		PolwithcheckColumn  = postgres.StringColumn("polwithcheck")
		allColumns          = postgres.ColumnList{OidColumn, PolnameColumn, PolrelidColumn, PolcmdColumn, PolpermissiveColumn, PolrolesColumn, PolqualColumn, PolwithcheckColumn}
		mutableColumns      = postgres.ColumnList{OidColumn, PolnameColumn, PolrelidColumn, PolcmdColumn, PolpermissiveColumn, PolrolesColumn, PolqualColumn, PolwithcheckColumn}
	)

	return pgPolicyTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Oid:           OidColumn,
		Polname:       PolnameColumn,
		Polrelid:      PolrelidColumn,
		Polcmd:        PolcmdColumn,
		Polpermissive: PolpermissiveColumn,
		Polroles:      PolrolesColumn,
		Polqual:       PolqualColumn,
		Polwithcheck:  PolwithcheckColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
