//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgRewrite = newPgRewriteTable()

type pgRewriteTable struct {
	postgres.Table

	//Columns
	Oid       postgres.ColumnString
	Rulename  postgres.ColumnString
	EvClass   postgres.ColumnString
	EvType    postgres.ColumnString
	EvEnabled postgres.ColumnString
	IsInstead postgres.ColumnBool
	EvQual    postgres.ColumnString
	EvAction  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgRewriteTable struct {
	pgRewriteTable

	EXCLUDED pgRewriteTable
}

// AS creates new PgRewriteTable with assigned alias
func (a *PgRewriteTable) AS(alias string) *PgRewriteTable {
	aliasTable := newPgRewriteTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgRewriteTable() *PgRewriteTable {
	return &PgRewriteTable{
		pgRewriteTable: newPgRewriteTableImpl("pg_catalog", "pg_rewrite"),
		EXCLUDED:       newPgRewriteTableImpl("", "excluded"),
	}
}

func newPgRewriteTableImpl(schemaName, tableName string) pgRewriteTable {
	var (
		OidColumn       = postgres.StringColumn("oid")
		RulenameColumn  = postgres.StringColumn("rulename")
		EvClassColumn   = postgres.StringColumn("ev_class")
		EvTypeColumn    = postgres.StringColumn("ev_type")
		EvEnabledColumn = postgres.StringColumn("ev_enabled")
		IsInsteadColumn = postgres.BoolColumn("is_instead")
		EvQualColumn    = postgres.StringColumn("ev_qual")
		EvActionColumn  = postgres.StringColumn("ev_action")
		allColumns      = postgres.ColumnList{OidColumn, RulenameColumn, EvClassColumn, EvTypeColumn, EvEnabledColumn, IsInsteadColumn, EvQualColumn, EvActionColumn}
		mutableColumns  = postgres.ColumnList{OidColumn, RulenameColumn, EvClassColumn, EvTypeColumn, EvEnabledColumn, IsInsteadColumn, EvQualColumn, EvActionColumn}
	)

	return pgRewriteTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Oid:       OidColumn,
		Rulename:  RulenameColumn,
		EvClass:   EvClassColumn,
		EvType:    EvTypeColumn,
		EvEnabled: EvEnabledColumn,
		IsInstead: IsInsteadColumn,
		EvQual:    EvQualColumn,
		EvAction:  EvActionColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
