//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgShdescription = newPgShdescriptionTable()

type PgShdescriptionTable struct {
	postgres.Table

	//Columns
	Objoid      postgres.ColumnString
	Classoid    postgres.ColumnString
	Description postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgShdescriptionTable with assigned alias
func (a *PgShdescriptionTable) AS(alias string) *PgShdescriptionTable {
	aliasTable := newPgShdescriptionTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgShdescriptionTable() *PgShdescriptionTable {
	var (
		ObjoidColumn      = postgres.StringColumn("objoid")
		ClassoidColumn    = postgres.StringColumn("classoid")
		DescriptionColumn = postgres.StringColumn("description")
	)

	return &PgShdescriptionTable{
		Table: postgres.NewTable("pg_catalog", "pg_shdescription", ObjoidColumn, ClassoidColumn, DescriptionColumn),

		//Columns
		Objoid:      ObjoidColumn,
		Classoid:    ClassoidColumn,
		Description: DescriptionColumn,

		AllColumns:     postgres.ColumnList{ObjoidColumn, ClassoidColumn, DescriptionColumn},
		MutableColumns: postgres.ColumnList{ObjoidColumn, ClassoidColumn, DescriptionColumn},
	}
}
