//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgSubscription = newPgSubscriptionTable()

type pgSubscriptionTable struct {
	postgres.Table

	//Columns
	Subdbid         postgres.ColumnString
	Subname         postgres.ColumnString
	Subowner        postgres.ColumnString
	Subenabled      postgres.ColumnBool
	Subslotname     postgres.ColumnString
	Subpublications postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgSubscriptionTable struct {
	pgSubscriptionTable

	EXCLUDED pgSubscriptionTable
}

// AS creates new PgSubscriptionTable with assigned alias
func (a *PgSubscriptionTable) AS(alias string) *PgSubscriptionTable {
	aliasTable := newPgSubscriptionTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgSubscriptionTable() *PgSubscriptionTable {
	return &PgSubscriptionTable{
		pgSubscriptionTable: newPgSubscriptionTableImpl("pg_catalog", "pg_subscription"),
		EXCLUDED:            newPgSubscriptionTableImpl("", "excluded"),
	}
}

func newPgSubscriptionTableImpl(schemaName, tableName string) pgSubscriptionTable {
	var (
		SubdbidColumn         = postgres.StringColumn("subdbid")
		SubnameColumn         = postgres.StringColumn("subname")
		SubownerColumn        = postgres.StringColumn("subowner")
		SubenabledColumn      = postgres.BoolColumn("subenabled")
		SubslotnameColumn     = postgres.StringColumn("subslotname")
		SubpublicationsColumn = postgres.StringColumn("subpublications")
		allColumns            = postgres.ColumnList{SubdbidColumn, SubnameColumn, SubownerColumn, SubenabledColumn, SubslotnameColumn, SubpublicationsColumn}
		mutableColumns        = postgres.ColumnList{SubdbidColumn, SubnameColumn, SubownerColumn, SubenabledColumn, SubslotnameColumn, SubpublicationsColumn}
	)

	return pgSubscriptionTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Subdbid:         SubdbidColumn,
		Subname:         SubnameColumn,
		Subowner:        SubownerColumn,
		Subenabled:      SubenabledColumn,
		Subslotname:     SubslotnameColumn,
		Subpublications: SubpublicationsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
