//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var PgShdepend = newPgShdependTable()

type pgShdependTable struct {
	postgres.Table

	//Columns
	Dbid       postgres.ColumnString
	Classid    postgres.ColumnString
	Objid      postgres.ColumnString
	Objsubid   postgres.ColumnInteger
	Refclassid postgres.ColumnString
	Refobjid   postgres.ColumnString
	Deptype    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type PgShdependTable struct {
	pgShdependTable

	EXCLUDED pgShdependTable
}

// AS creates new PgShdependTable with assigned alias
func (a *PgShdependTable) AS(alias string) *PgShdependTable {
	aliasTable := newPgShdependTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newPgShdependTable() *PgShdependTable {
	return &PgShdependTable{
		pgShdependTable: newPgShdependTableImpl("pg_catalog", "pg_shdepend"),
		EXCLUDED:        newPgShdependTableImpl("", "excluded"),
	}
}

func newPgShdependTableImpl(schemaName, tableName string) pgShdependTable {
	var (
		DbidColumn       = postgres.StringColumn("dbid")
		ClassidColumn    = postgres.StringColumn("classid")
		ObjidColumn      = postgres.StringColumn("objid")
		ObjsubidColumn   = postgres.IntegerColumn("objsubid")
		RefclassidColumn = postgres.StringColumn("refclassid")
		RefobjidColumn   = postgres.StringColumn("refobjid")
		DeptypeColumn    = postgres.StringColumn("deptype")
		allColumns       = postgres.ColumnList{DbidColumn, ClassidColumn, ObjidColumn, ObjsubidColumn, RefclassidColumn, RefobjidColumn, DeptypeColumn}
		mutableColumns   = postgres.ColumnList{DbidColumn, ClassidColumn, ObjidColumn, ObjsubidColumn, RefclassidColumn, RefobjidColumn, DeptypeColumn}
	)

	return pgShdependTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		Dbid:       DbidColumn,
		Classid:    ClassidColumn,
		Objid:      ObjidColumn,
		Objsubid:   ObjsubidColumn,
		Refclassid: RefclassidColumn,
		Refobjid:   RefobjidColumn,
		Deptype:    DeptypeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
