//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgStatisticExt = newPgStatisticExtTable()

type PgStatisticExtTable struct {
	postgres.Table

	//Columns
	Oid          postgres.ColumnString
	Stxrelid     postgres.ColumnString
	Stxname      postgres.ColumnString
	Stxnamespace postgres.ColumnString
	Stxowner     postgres.ColumnString
	Stxkeys      postgres.ColumnString
	Stxkind      postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgStatisticExtTable with assigned alias
func (a *PgStatisticExtTable) AS(alias string) *PgStatisticExtTable {
	aliasTable := newPgStatisticExtTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgStatisticExtTable() *PgStatisticExtTable {
	var (
		OidColumn          = postgres.StringColumn("oid")
		StxrelidColumn     = postgres.StringColumn("stxrelid")
		StxnameColumn      = postgres.StringColumn("stxname")
		StxnamespaceColumn = postgres.StringColumn("stxnamespace")
		StxownerColumn     = postgres.StringColumn("stxowner")
		StxkeysColumn      = postgres.StringColumn("stxkeys")
		StxkindColumn      = postgres.StringColumn("stxkind")
	)

	return &PgStatisticExtTable{
		Table: postgres.NewTable("pg_catalog", "pg_statistic_ext", OidColumn, StxrelidColumn, StxnameColumn, StxnamespaceColumn, StxownerColumn, StxkeysColumn, StxkindColumn),

		//Columns
		Oid:          OidColumn,
		Stxrelid:     StxrelidColumn,
		Stxname:      StxnameColumn,
		Stxnamespace: StxnamespaceColumn,
		Stxowner:     StxownerColumn,
		Stxkeys:      StxkeysColumn,
		Stxkind:      StxkindColumn,

		AllColumns:     postgres.ColumnList{OidColumn, StxrelidColumn, StxnameColumn, StxnamespaceColumn, StxownerColumn, StxkeysColumn, StxkindColumn},
		MutableColumns: postgres.ColumnList{OidColumn, StxrelidColumn, StxnameColumn, StxnamespaceColumn, StxownerColumn, StxkeysColumn, StxkindColumn},
	}
}
