//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SchemaMigrations = newSchemaMigrationsTable()

type schemaMigrationsTable struct {
	postgres.Table

	//Columns
	ID        postgres.ColumnInteger
	VersionID postgres.ColumnInteger
	IsApplied postgres.ColumnBool
	Tstamp    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SchemaMigrationsTable struct {
	schemaMigrationsTable

	EXCLUDED schemaMigrationsTable
}

// AS creates new SchemaMigrationsTable with assigned alias
func (a *SchemaMigrationsTable) AS(alias string) *SchemaMigrationsTable {
	aliasTable := newSchemaMigrationsTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newSchemaMigrationsTable() *SchemaMigrationsTable {
	return &SchemaMigrationsTable{
		schemaMigrationsTable: newSchemaMigrationsTableImpl("pgsink", "schema_migrations"),
		EXCLUDED:              newSchemaMigrationsTableImpl("", "excluded"),
	}
}

func newSchemaMigrationsTableImpl(schemaName, tableName string) schemaMigrationsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		VersionIDColumn = postgres.IntegerColumn("version_id")
		IsAppliedColumn = postgres.BoolColumn("is_applied")
		TstampColumn    = postgres.TimestampColumn("tstamp")
		allColumns      = postgres.ColumnList{IDColumn, VersionIDColumn, IsAppliedColumn, TstampColumn}
		mutableColumns  = postgres.ColumnList{VersionIDColumn, IsAppliedColumn, TstampColumn}
	)

	return schemaMigrationsTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		ID:        IDColumn,
		VersionID: VersionIDColumn,
		IsApplied: IsAppliedColumn,
		Tstamp:    TstampColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
