{
 "title": "pg2sink",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "interval", "query": "15s,1m,5m,15m" }
  ]
 },
 "panels": [
  { "title": "Streaming", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Logical Messages Received",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (type) (rate(pg2sink_subscription_receive_message_total[$interval]))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  { "title": "Imports", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Postgres Rows Read",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pg2sink_importer_work_postgres_rows_read_total[$interval]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Sink Flushes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (table) (rate(pg2sink_importer_work_sink_flush_duration_seconds_count[$interval]))",
     "legendFormat": "{{ table }}"
    }
   ]
  },
  {
   "title": "Sink Flush Duration",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum by (table) (rate(pg2sink_importer_work_sink_flush_duration_seconds_bucket[$interval]))",
     "legendFormat": "{{ table }}"
    }
   ]
  }
 ]
}