//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package view

import (
	"github.com/go-jet/jet/v2/postgres"
)

var ColumnDomainUsage = newColumnDomainUsageTable()

type columnDomainUsageTable struct {
	postgres.Table

	//Columns
	DomainCatalog postgres.ColumnString
	DomainSchema  postgres.ColumnString
	DomainName    postgres.ColumnString
	TableCatalog  postgres.ColumnString
	TableSchema   postgres.ColumnString
	TableName     postgres.ColumnString
	ColumnName    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type ColumnDomainUsageTable struct {
	columnDomainUsageTable

	EXCLUDED columnDomainUsageTable
}

// AS creates new ColumnDomainUsageTable with assigned alias
func (a *ColumnDomainUsageTable) AS(alias string) *ColumnDomainUsageTable {
	aliasTable := newColumnDomainUsageTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newColumnDomainUsageTable() *ColumnDomainUsageTable {
	return &ColumnDomainUsageTable{
		columnDomainUsageTable: newColumnDomainUsageTableImpl("information_schema", "column_domain_usage"),
		EXCLUDED:               newColumnDomainUsageTableImpl("", "excluded"),
	}
}

func newColumnDomainUsageTableImpl(schemaName, tableName string) columnDomainUsageTable {
	var (
		DomainCatalogColumn = postgres.StringColumn("domain_catalog")
		DomainSchemaColumn  = postgres.StringColumn("domain_schema")
		DomainNameColumn    = postgres.StringColumn("domain_name")
		TableCatalogColumn  = postgres.StringColumn("table_catalog")
		TableSchemaColumn   = postgres.StringColumn("table_schema")
		TableNameColumn     = postgres.StringColumn("table_name")
		ColumnNameColumn    = postgres.StringColumn("column_name")
		allColumns          = postgres.ColumnList{DomainCatalogColumn, DomainSchemaColumn, DomainNameColumn, TableCatalogColumn, TableSchemaColumn, TableNameColumn, ColumnNameColumn}
		mutableColumns      = postgres.ColumnList{DomainCatalogColumn, DomainSchemaColumn, DomainNameColumn, TableCatalogColumn, TableSchemaColumn, TableNameColumn, ColumnNameColumn}
	)

	return columnDomainUsageTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		DomainCatalog: DomainCatalogColumn,
		DomainSchema:  DomainSchemaColumn,
		DomainName:    DomainNameColumn,
		TableCatalog:  TableCatalogColumn,
		TableSchema:   TableSchemaColumn,
		TableName:     TableNameColumn,
		ColumnName:    ColumnNameColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
