//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgClass struct {
	Oid                 string
	Relname             string
	Relnamespace        string
	Reltype             string
	Reloftype           string
	Relowner            string
	Relam               string
	Relfilenode         string
	Reltablespace       string
	Relpages            int32
	Reltuples           float32
	Relallvisible       int32
	Reltoastrelid       string
	Relhasindex         bool
	Relisshared         bool
	Relpersistence      string
	Relkind             string
	Relnatts            int16
	Relchecks           int16
	Relhasrules         bool
	Relhastriggers      bool
	Relhassubclass      bool
	Relrowsecurity      bool
	Relforcerowsecurity bool
	Relispopulated      bool
	Relreplident        string
	Relispartition      bool
	Relrewrite          string
	Relfrozenxid        string
	Relminmxid          string
	Relacl              *string
	Reloptions          *string
	Relpartbound        *string
}
