//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgPartitionedTable struct {
	Partrelid     string
	Partstrat     string
	Partnatts     int16
	Partdefid     string
	Partattrs     string
	Partclass     string
	Partcollation string
	Partexprs     *string
}
