//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgRewrite struct {
	Oid       string
	Rulename  string
	EvClass   string
	EvType    string
	EvEnabled string
	IsInstead bool
	EvQual    string
	EvAction  string
}
