//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type PgStatWalReceiver struct {
	Pid                *int32
	Status             *string
	ReceiveStartLsn    *string
	ReceiveStartTli    *int32
	ReceivedLsn        *string
	ReceivedTli        *int32
	LastMsgSendTime    *time.Time
	LastMsgReceiptTime *time.Time
	LatestEndLsn       *string
	LatestEndTime      *time.Time
	SlotName           *string
	SenderHost         *string
	SenderPort         *int32
	Conninfo           *string
}
