//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgSubscription struct {
	Subdbid         string
	Subname         string
	Subowner        string
	Subenabled      bool
	Subslotname     string
	Subpublications string
}
