//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type PgStatUserIndexes struct {
	Relid        *string
	Indexrelid   *string
	Schemaname   *string
	Relname      *string
	Indexrelname *string
	IdxScan      *int64
	IdxTupRead   *int64
	IdxTupFetch  *int64
}
