/* tslint:disable */
/* eslint-disable */
/**
 * pgsink
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CheckResponseBody,
    CheckResponseBodyFromJSON,
    CheckResponseBodyToJSON,
} from '../models';

/**
 * 
 */
export class HealthApi extends runtime.BaseAPI {

    /**
     * Health check for probes
     * Check Health
     */
    async healthCheckRaw(): Promise<runtime.ApiResponse<CheckResponseBody>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/health/check`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });

        return new runtime.JSONApiResponse(response, (jsonValue) => CheckResponseBodyFromJSON(jsonValue));
    }

    /**
     * Health check for probes
     * Check Health
     */
    async healthCheck(): Promise<CheckResponseBody> {
        const response = await this.healthCheckRaw();
        return await response.value();
    }

}
