//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var SQLPackages = newSQLPackagesTable()

type SQLPackagesTable struct {
	postgres.Table

	//Columns
	FeatureID    postgres.ColumnString
	FeatureName  postgres.ColumnString
	IsSupported  postgres.ColumnString
	IsVerifiedBy postgres.ColumnString
	Comments     postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new SQLPackagesTable with assigned alias
func (a *SQLPackagesTable) AS(alias string) *SQLPackagesTable {
	aliasTable := newSQLPackagesTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newSQLPackagesTable() *SQLPackagesTable {
	var (
		FeatureIDColumn    = postgres.StringColumn("feature_id")
		FeatureNameColumn  = postgres.StringColumn("feature_name")
		IsSupportedColumn  = postgres.StringColumn("is_supported")
		IsVerifiedByColumn = postgres.StringColumn("is_verified_by")
		CommentsColumn     = postgres.StringColumn("comments")
	)

	return &SQLPackagesTable{
		Table: postgres.NewTable("information_schema", "sql_packages", FeatureIDColumn, FeatureNameColumn, IsSupportedColumn, IsVerifiedByColumn, CommentsColumn),

		//Columns
		FeatureID:    FeatureIDColumn,
		FeatureName:  FeatureNameColumn,
		IsSupported:  IsSupportedColumn,
		IsVerifiedBy: IsVerifiedByColumn,
		Comments:     CommentsColumn,

		AllColumns:     postgres.ColumnList{FeatureIDColumn, FeatureNameColumn, IsSupportedColumn, IsVerifiedByColumn, CommentsColumn},
		MutableColumns: postgres.ColumnList{FeatureIDColumn, FeatureNameColumn, IsSupportedColumn, IsVerifiedByColumn, CommentsColumn},
	}
}
