//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var SQLImplementationInfo = newSQLImplementationInfoTable()

type SQLImplementationInfoTable struct {
	postgres.Table

	//Columns
	ImplementationInfoID   postgres.ColumnString
	ImplementationInfoName postgres.ColumnString
	IntegerValue           postgres.ColumnInteger
	CharacterValue         postgres.ColumnString
	Comments               postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new SQLImplementationInfoTable with assigned alias
func (a *SQLImplementationInfoTable) AS(alias string) *SQLImplementationInfoTable {
	aliasTable := newSQLImplementationInfoTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newSQLImplementationInfoTable() *SQLImplementationInfoTable {
	var (
		ImplementationInfoIDColumn   = postgres.StringColumn("implementation_info_id")
		ImplementationInfoNameColumn = postgres.StringColumn("implementation_info_name")
		IntegerValueColumn           = postgres.IntegerColumn("integer_value")
		CharacterValueColumn         = postgres.StringColumn("character_value")
		CommentsColumn               = postgres.StringColumn("comments")
	)

	return &SQLImplementationInfoTable{
		Table: postgres.NewTable("information_schema", "sql_implementation_info", ImplementationInfoIDColumn, ImplementationInfoNameColumn, IntegerValueColumn, CharacterValueColumn, CommentsColumn),

		//Columns
		ImplementationInfoID:   ImplementationInfoIDColumn,
		ImplementationInfoName: ImplementationInfoNameColumn,
		IntegerValue:           IntegerValueColumn,
		CharacterValue:         CharacterValueColumn,
		Comments:               CommentsColumn,

		AllColumns:     postgres.ColumnList{ImplementationInfoIDColumn, ImplementationInfoNameColumn, IntegerValueColumn, CharacterValueColumn, CommentsColumn},
		MutableColumns: postgres.ColumnList{ImplementationInfoIDColumn, ImplementationInfoNameColumn, IntegerValueColumn, CharacterValueColumn, CommentsColumn},
	}
}
