//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 09:15:06 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var SQLFeatures = newSQLFeaturesTable()

type SQLFeaturesTable struct {
	postgres.Table

	//Columns
	FeatureID      postgres.ColumnString
	FeatureName    postgres.ColumnString
	SubFeatureID   postgres.ColumnString
	SubFeatureName postgres.ColumnString
	IsSupported    postgres.ColumnString
	IsVerifiedBy   postgres.ColumnString
	Comments       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new SQLFeaturesTable with assigned alias
func (a *SQLFeaturesTable) AS(alias string) *SQLFeaturesTable {
	aliasTable := newSQLFeaturesTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newSQLFeaturesTable() *SQLFeaturesTable {
	var (
		FeatureIDColumn      = postgres.StringColumn("feature_id")
		FeatureNameColumn    = postgres.StringColumn("feature_name")
		SubFeatureIDColumn   = postgres.StringColumn("sub_feature_id")
		SubFeatureNameColumn = postgres.StringColumn("sub_feature_name")
		IsSupportedColumn    = postgres.StringColumn("is_supported")
		IsVerifiedByColumn   = postgres.StringColumn("is_verified_by")
		CommentsColumn       = postgres.StringColumn("comments")
	)

	return &SQLFeaturesTable{
		Table: postgres.NewTable("information_schema", "sql_features", FeatureIDColumn, FeatureNameColumn, SubFeatureIDColumn, SubFeatureNameColumn, IsSupportedColumn, IsVerifiedByColumn, CommentsColumn),

		//Columns
		FeatureID:      FeatureIDColumn,
		FeatureName:    FeatureNameColumn,
		SubFeatureID:   SubFeatureIDColumn,
		SubFeatureName: SubFeatureNameColumn,
		IsSupported:    IsSupportedColumn,
		IsVerifiedBy:   IsVerifiedByColumn,
		Comments:       CommentsColumn,

		AllColumns:     postgres.ColumnList{FeatureIDColumn, FeatureNameColumn, SubFeatureIDColumn, SubFeatureNameColumn, IsSupportedColumn, IsVerifiedByColumn, CommentsColumn},
		MutableColumns: postgres.ColumnList{FeatureIDColumn, FeatureNameColumn, SubFeatureIDColumn, SubFeatureNameColumn, IsSupportedColumn, IsVerifiedByColumn, CommentsColumn},
	}
}
