//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var SQLFeatures = newSQLFeaturesTable()

type sQLFeaturesTable struct {
	postgres.Table

	//Columns
	FeatureID      postgres.ColumnString
	FeatureName    postgres.ColumnString
	SubFeatureID   postgres.ColumnString
	SubFeatureName postgres.ColumnString
	IsSupported    postgres.ColumnString
	IsVerifiedBy   postgres.ColumnString
	Comments       postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

type SQLFeaturesTable struct {
	sQLFeaturesTable

	EXCLUDED sQLFeaturesTable
}

// AS creates new SQLFeaturesTable with assigned alias
func (a *SQLFeaturesTable) AS(alias string) *SQLFeaturesTable {
	aliasTable := newSQLFeaturesTable()
	aliasTable.Table.AS(alias)
	return aliasTable
}

func newSQLFeaturesTable() *SQLFeaturesTable {
	return &SQLFeaturesTable{
		sQLFeaturesTable: newSQLFeaturesTableImpl("information_schema", "sql_features"),
		EXCLUDED:         newSQLFeaturesTableImpl("", "excluded"),
	}
}

func newSQLFeaturesTableImpl(schemaName, tableName string) sQLFeaturesTable {
	var (
		FeatureIDColumn      = postgres.StringColumn("feature_id")
		FeatureNameColumn    = postgres.StringColumn("feature_name")
		SubFeatureIDColumn   = postgres.StringColumn("sub_feature_id")
		SubFeatureNameColumn = postgres.StringColumn("sub_feature_name")
		IsSupportedColumn    = postgres.StringColumn("is_supported")
		IsVerifiedByColumn   = postgres.StringColumn("is_verified_by")
		CommentsColumn       = postgres.StringColumn("comments")
		allColumns           = postgres.ColumnList{FeatureIDColumn, FeatureNameColumn, SubFeatureIDColumn, SubFeatureNameColumn, IsSupportedColumn, IsVerifiedByColumn, CommentsColumn}
		mutableColumns       = postgres.ColumnList{FeatureIDColumn, FeatureNameColumn, SubFeatureIDColumn, SubFeatureNameColumn, IsSupportedColumn, IsVerifiedByColumn, CommentsColumn}
	)

	return sQLFeaturesTable{
		Table: postgres.NewTable(schemaName, tableName, allColumns...),

		//Columns
		FeatureID:      FeatureIDColumn,
		FeatureName:    FeatureNameColumn,
		SubFeatureID:   SubFeatureIDColumn,
		SubFeatureName: SubFeatureNameColumn,
		IsSupported:    IsSupportedColumn,
		IsVerifiedBy:   IsVerifiedByColumn,
		Comments:       CommentsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
