//
// Code generated by go-jet DO NOT EDIT.
// Generated at Sunday, 10-May-20 16:40:01 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var SchemaMigrations = newSchemaMigrationsTable()

type SchemaMigrationsTable struct {
	postgres.Table

	//Columns
	ID        postgres.ColumnInteger
	VersionID postgres.ColumnInteger
	IsApplied postgres.ColumnBool
	Tstamp    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new SchemaMigrationsTable with assigned alias
func (a *SchemaMigrationsTable) AS(alias string) *SchemaMigrationsTable {
	aliasTable := newSchemaMigrationsTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newSchemaMigrationsTable() *SchemaMigrationsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		VersionIDColumn = postgres.IntegerColumn("version_id")
		IsAppliedColumn = postgres.BoolColumn("is_applied")
		TstampColumn    = postgres.TimestampColumn("tstamp")
	)

	return &SchemaMigrationsTable{
		Table: postgres.NewTable("pg2sink", "schema_migrations", IDColumn, VersionIDColumn, IsAppliedColumn, TstampColumn),

		//Columns
		ID:        IDColumn,
		VersionID: VersionIDColumn,
		IsApplied: IsAppliedColumn,
		Tstamp:    TstampColumn,

		AllColumns:     postgres.ColumnList{IDColumn, VersionIDColumn, IsAppliedColumn, TstampColumn},
		MutableColumns: postgres.ColumnList{VersionIDColumn, IsAppliedColumn, TstampColumn},
	}
}
