//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgAuthMembers = newPgAuthMembersTable()

type PgAuthMembersTable struct {
	postgres.Table

	//Columns
	Roleid      postgres.ColumnString
	Member      postgres.ColumnString
	Grantor     postgres.ColumnString
	AdminOption postgres.ColumnBool

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgAuthMembersTable with assigned alias
func (a *PgAuthMembersTable) AS(alias string) *PgAuthMembersTable {
	aliasTable := newPgAuthMembersTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgAuthMembersTable() *PgAuthMembersTable {
	var (
		RoleidColumn      = postgres.StringColumn("roleid")
		MemberColumn      = postgres.StringColumn("member")
		GrantorColumn     = postgres.StringColumn("grantor")
		AdminOptionColumn = postgres.BoolColumn("admin_option")
	)

	return &PgAuthMembersTable{
		Table: postgres.NewTable("pg_catalog", "pg_auth_members", RoleidColumn, MemberColumn, GrantorColumn, AdminOptionColumn),

		//Columns
		Roleid:      RoleidColumn,
		Member:      MemberColumn,
		Grantor:     GrantorColumn,
		AdminOption: AdminOptionColumn,

		AllColumns:     postgres.ColumnList{RoleidColumn, MemberColumn, GrantorColumn, AdminOptionColumn},
		MutableColumns: postgres.ColumnList{RoleidColumn, MemberColumn, GrantorColumn, AdminOptionColumn},
	}
}
