//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgAm = newPgAmTable()

type PgAmTable struct {
	postgres.Table

	//Columns
	Oid       postgres.ColumnString
	Amname    postgres.ColumnString
	Amhandler postgres.ColumnString
	Amtype    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgAmTable with assigned alias
func (a *PgAmTable) AS(alias string) *PgAmTable {
	aliasTable := newPgAmTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgAmTable() *PgAmTable {
	var (
		OidColumn       = postgres.StringColumn("oid")
		AmnameColumn    = postgres.StringColumn("amname")
		AmhandlerColumn = postgres.StringColumn("amhandler")
		AmtypeColumn    = postgres.StringColumn("amtype")
	)

	return &PgAmTable{
		Table: postgres.NewTable("pg_catalog", "pg_am", OidColumn, AmnameColumn, AmhandlerColumn, AmtypeColumn),

		//Columns
		Oid:       OidColumn,
		Amname:    AmnameColumn,
		Amhandler: AmhandlerColumn,
		Amtype:    AmtypeColumn,

		AllColumns:     postgres.ColumnList{OidColumn, AmnameColumn, AmhandlerColumn, AmtypeColumn},
		MutableColumns: postgres.ColumnList{OidColumn, AmnameColumn, AmhandlerColumn, AmtypeColumn},
	}
}
