//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgClass = newPgClassTable()

type PgClassTable struct {
	postgres.Table

	//Columns
	Oid                 postgres.ColumnString
	Relname             postgres.ColumnString
	Relnamespace        postgres.ColumnString
	Reltype             postgres.ColumnString
	Reloftype           postgres.ColumnString
	Relowner            postgres.ColumnString
	Relam               postgres.ColumnString
	Relfilenode         postgres.ColumnString
	Reltablespace       postgres.ColumnString
	Relpages            postgres.ColumnInteger
	Reltuples           postgres.ColumnFloat
	Relallvisible       postgres.ColumnInteger
	Reltoastrelid       postgres.ColumnString
	Relhasindex         postgres.ColumnBool
	Relisshared         postgres.ColumnBool
	Relpersistence      postgres.ColumnString
	Relkind             postgres.ColumnString
	Relnatts            postgres.ColumnInteger
	Relchecks           postgres.ColumnInteger
	Relhasrules         postgres.ColumnBool
	Relhastriggers      postgres.ColumnBool
	Relhassubclass      postgres.ColumnBool
	Relrowsecurity      postgres.ColumnBool
	Relforcerowsecurity postgres.ColumnBool
	Relispopulated      postgres.ColumnBool
	Relreplident        postgres.ColumnString
	Relispartition      postgres.ColumnBool
	Relrewrite          postgres.ColumnString
	Relfrozenxid        postgres.ColumnString
	Relminmxid          postgres.ColumnString
	Relacl              postgres.ColumnString
	Reloptions          postgres.ColumnString
	Relpartbound        postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgClassTable with assigned alias
func (a *PgClassTable) AS(alias string) *PgClassTable {
	aliasTable := newPgClassTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgClassTable() *PgClassTable {
	var (
		OidColumn                 = postgres.StringColumn("oid")
		RelnameColumn             = postgres.StringColumn("relname")
		RelnamespaceColumn        = postgres.StringColumn("relnamespace")
		ReltypeColumn             = postgres.StringColumn("reltype")
		ReloftypeColumn           = postgres.StringColumn("reloftype")
		RelownerColumn            = postgres.StringColumn("relowner")
		RelamColumn               = postgres.StringColumn("relam")
		RelfilenodeColumn         = postgres.StringColumn("relfilenode")
		ReltablespaceColumn       = postgres.StringColumn("reltablespace")
		RelpagesColumn            = postgres.IntegerColumn("relpages")
		ReltuplesColumn           = postgres.FloatColumn("reltuples")
		RelallvisibleColumn       = postgres.IntegerColumn("relallvisible")
		ReltoastrelidColumn       = postgres.StringColumn("reltoastrelid")
		RelhasindexColumn         = postgres.BoolColumn("relhasindex")
		RelissharedColumn         = postgres.BoolColumn("relisshared")
		RelpersistenceColumn      = postgres.StringColumn("relpersistence")
		RelkindColumn             = postgres.StringColumn("relkind")
		RelnattsColumn            = postgres.IntegerColumn("relnatts")
		RelchecksColumn           = postgres.IntegerColumn("relchecks")
		RelhasrulesColumn         = postgres.BoolColumn("relhasrules")
		RelhastriggersColumn      = postgres.BoolColumn("relhastriggers")
		RelhassubclassColumn      = postgres.BoolColumn("relhassubclass")
		RelrowsecurityColumn      = postgres.BoolColumn("relrowsecurity")
		RelforcerowsecurityColumn = postgres.BoolColumn("relforcerowsecurity")
		RelispopulatedColumn      = postgres.BoolColumn("relispopulated")
		RelreplidentColumn        = postgres.StringColumn("relreplident")
		RelispartitionColumn      = postgres.BoolColumn("relispartition")
		RelrewriteColumn          = postgres.StringColumn("relrewrite")
		RelfrozenxidColumn        = postgres.StringColumn("relfrozenxid")
		RelminmxidColumn          = postgres.StringColumn("relminmxid")
		RelaclColumn              = postgres.StringColumn("relacl")
		ReloptionsColumn          = postgres.StringColumn("reloptions")
		RelpartboundColumn        = postgres.StringColumn("relpartbound")
	)

	return &PgClassTable{
		Table: postgres.NewTable("pg_catalog", "pg_class", OidColumn, RelnameColumn, RelnamespaceColumn, ReltypeColumn, ReloftypeColumn, RelownerColumn, RelamColumn, RelfilenodeColumn, ReltablespaceColumn, RelpagesColumn, ReltuplesColumn, RelallvisibleColumn, ReltoastrelidColumn, RelhasindexColumn, RelissharedColumn, RelpersistenceColumn, RelkindColumn, RelnattsColumn, RelchecksColumn, RelhasrulesColumn, RelhastriggersColumn, RelhassubclassColumn, RelrowsecurityColumn, RelforcerowsecurityColumn, RelispopulatedColumn, RelreplidentColumn, RelispartitionColumn, RelrewriteColumn, RelfrozenxidColumn, RelminmxidColumn, RelaclColumn, ReloptionsColumn, RelpartboundColumn),

		//Columns
		Oid:                 OidColumn,
		Relname:             RelnameColumn,
		Relnamespace:        RelnamespaceColumn,
		Reltype:             ReltypeColumn,
		Reloftype:           ReloftypeColumn,
		Relowner:            RelownerColumn,
		Relam:               RelamColumn,
		Relfilenode:         RelfilenodeColumn,
		Reltablespace:       ReltablespaceColumn,
		Relpages:            RelpagesColumn,
		Reltuples:           ReltuplesColumn,
		Relallvisible:       RelallvisibleColumn,
		Reltoastrelid:       ReltoastrelidColumn,
		Relhasindex:         RelhasindexColumn,
		Relisshared:         RelissharedColumn,
		Relpersistence:      RelpersistenceColumn,
		Relkind:             RelkindColumn,
		Relnatts:            RelnattsColumn,
		Relchecks:           RelchecksColumn,
		Relhasrules:         RelhasrulesColumn,
		Relhastriggers:      RelhastriggersColumn,
		Relhassubclass:      RelhassubclassColumn,
		Relrowsecurity:      RelrowsecurityColumn,
		Relforcerowsecurity: RelforcerowsecurityColumn,
		Relispopulated:      RelispopulatedColumn,
		Relreplident:        RelreplidentColumn,
		Relispartition:      RelispartitionColumn,
		Relrewrite:          RelrewriteColumn,
		Relfrozenxid:        RelfrozenxidColumn,
		Relminmxid:          RelminmxidColumn,
		Relacl:              RelaclColumn,
		Reloptions:          ReloptionsColumn,
		Relpartbound:        RelpartboundColumn,

		AllColumns:     postgres.ColumnList{OidColumn, RelnameColumn, RelnamespaceColumn, ReltypeColumn, ReloftypeColumn, RelownerColumn, RelamColumn, RelfilenodeColumn, ReltablespaceColumn, RelpagesColumn, ReltuplesColumn, RelallvisibleColumn, ReltoastrelidColumn, RelhasindexColumn, RelissharedColumn, RelpersistenceColumn, RelkindColumn, RelnattsColumn, RelchecksColumn, RelhasrulesColumn, RelhastriggersColumn, RelhassubclassColumn, RelrowsecurityColumn, RelforcerowsecurityColumn, RelispopulatedColumn, RelreplidentColumn, RelispartitionColumn, RelrewriteColumn, RelfrozenxidColumn, RelminmxidColumn, RelaclColumn, ReloptionsColumn, RelpartboundColumn},
		MutableColumns: postgres.ColumnList{OidColumn, RelnameColumn, RelnamespaceColumn, ReltypeColumn, ReloftypeColumn, RelownerColumn, RelamColumn, RelfilenodeColumn, ReltablespaceColumn, RelpagesColumn, ReltuplesColumn, RelallvisibleColumn, ReltoastrelidColumn, RelhasindexColumn, RelissharedColumn, RelpersistenceColumn, RelkindColumn, RelnattsColumn, RelchecksColumn, RelhasrulesColumn, RelhastriggersColumn, RelhassubclassColumn, RelrowsecurityColumn, RelforcerowsecurityColumn, RelispopulatedColumn, RelreplidentColumn, RelispartitionColumn, RelrewriteColumn, RelfrozenxidColumn, RelminmxidColumn, RelaclColumn, ReloptionsColumn, RelpartboundColumn},
	}
}
