//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgDbRoleSetting = newPgDbRoleSettingTable()

type PgDbRoleSettingTable struct {
	postgres.Table

	//Columns
	Setdatabase postgres.ColumnString
	Setrole     postgres.ColumnString
	Setconfig   postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgDbRoleSettingTable with assigned alias
func (a *PgDbRoleSettingTable) AS(alias string) *PgDbRoleSettingTable {
	aliasTable := newPgDbRoleSettingTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgDbRoleSettingTable() *PgDbRoleSettingTable {
	var (
		SetdatabaseColumn = postgres.StringColumn("setdatabase")
		SetroleColumn     = postgres.StringColumn("setrole")
		SetconfigColumn   = postgres.StringColumn("setconfig")
	)

	return &PgDbRoleSettingTable{
		Table: postgres.NewTable("pg_catalog", "pg_db_role_setting", SetdatabaseColumn, SetroleColumn, SetconfigColumn),

		//Columns
		Setdatabase: SetdatabaseColumn,
		Setrole:     SetroleColumn,
		Setconfig:   SetconfigColumn,

		AllColumns:     postgres.ColumnList{SetdatabaseColumn, SetroleColumn, SetconfigColumn},
		MutableColumns: postgres.ColumnList{SetdatabaseColumn, SetroleColumn, SetconfigColumn},
	}
}
