//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgForeignTable = newPgForeignTableTable()

type PgForeignTableTable struct {
	postgres.Table

	//Columns
	Ftrelid   postgres.ColumnString
	Ftserver  postgres.ColumnString
	Ftoptions postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgForeignTableTable with assigned alias
func (a *PgForeignTableTable) AS(alias string) *PgForeignTableTable {
	aliasTable := newPgForeignTableTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgForeignTableTable() *PgForeignTableTable {
	var (
		FtrelidColumn   = postgres.StringColumn("ftrelid")
		FtserverColumn  = postgres.StringColumn("ftserver")
		FtoptionsColumn = postgres.StringColumn("ftoptions")
	)

	return &PgForeignTableTable{
		Table: postgres.NewTable("pg_catalog", "pg_foreign_table", FtrelidColumn, FtserverColumn, FtoptionsColumn),

		//Columns
		Ftrelid:   FtrelidColumn,
		Ftserver:  FtserverColumn,
		Ftoptions: FtoptionsColumn,

		AllColumns:     postgres.ColumnList{FtrelidColumn, FtserverColumn, FtoptionsColumn},
		MutableColumns: postgres.ColumnList{FtrelidColumn, FtserverColumn, FtoptionsColumn},
	}
}
