//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgPolicy = newPgPolicyTable()

type PgPolicyTable struct {
	postgres.Table

	//Columns
	Oid           postgres.ColumnString
	Polname       postgres.ColumnString
	Polrelid      postgres.ColumnString
	Polcmd        postgres.ColumnString
	Polpermissive postgres.ColumnBool
	Polroles      postgres.ColumnString
	Polqual       postgres.ColumnString
	Polwithcheck  postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgPolicyTable with assigned alias
func (a *PgPolicyTable) AS(alias string) *PgPolicyTable {
	aliasTable := newPgPolicyTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgPolicyTable() *PgPolicyTable {
	var (
		OidColumn           = postgres.StringColumn("oid")
		PolnameColumn       = postgres.StringColumn("polname")
		PolrelidColumn      = postgres.StringColumn("polrelid")
		PolcmdColumn        = postgres.StringColumn("polcmd")
		PolpermissiveColumn = postgres.BoolColumn("polpermissive")
		PolrolesColumn      = postgres.StringColumn("polroles")
		PolqualColumn       = postgres.StringColumn("polqual")
		PolwithcheckColumn  = postgres.StringColumn("polwithcheck")
	)

	return &PgPolicyTable{
		Table: postgres.NewTable("pg_catalog", "pg_policy", OidColumn, PolnameColumn, PolrelidColumn, PolcmdColumn, PolpermissiveColumn, PolrolesColumn, PolqualColumn, PolwithcheckColumn),

		//Columns
		Oid:           OidColumn,
		Polname:       PolnameColumn,
		Polrelid:      PolrelidColumn,
		Polcmd:        PolcmdColumn,
		Polpermissive: PolpermissiveColumn,
		Polroles:      PolrolesColumn,
		Polqual:       PolqualColumn,
		Polwithcheck:  PolwithcheckColumn,

		AllColumns:     postgres.ColumnList{OidColumn, PolnameColumn, PolrelidColumn, PolcmdColumn, PolpermissiveColumn, PolrolesColumn, PolqualColumn, PolwithcheckColumn},
		MutableColumns: postgres.ColumnList{OidColumn, PolnameColumn, PolrelidColumn, PolcmdColumn, PolpermissiveColumn, PolrolesColumn, PolqualColumn, PolwithcheckColumn},
	}
}
