//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgSubscription = newPgSubscriptionTable()

type PgSubscriptionTable struct {
	postgres.Table

	//Columns
	Subdbid         postgres.ColumnString
	Subname         postgres.ColumnString
	Subowner        postgres.ColumnString
	Subenabled      postgres.ColumnBool
	Subslotname     postgres.ColumnString
	Subpublications postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgSubscriptionTable with assigned alias
func (a *PgSubscriptionTable) AS(alias string) *PgSubscriptionTable {
	aliasTable := newPgSubscriptionTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgSubscriptionTable() *PgSubscriptionTable {
	var (
		SubdbidColumn         = postgres.StringColumn("subdbid")
		SubnameColumn         = postgres.StringColumn("subname")
		SubownerColumn        = postgres.StringColumn("subowner")
		SubenabledColumn      = postgres.BoolColumn("subenabled")
		SubslotnameColumn     = postgres.StringColumn("subslotname")
		SubpublicationsColumn = postgres.StringColumn("subpublications")
	)

	return &PgSubscriptionTable{
		Table: postgres.NewTable("pg_catalog", "pg_subscription", SubdbidColumn, SubnameColumn, SubownerColumn, SubenabledColumn, SubslotnameColumn, SubpublicationsColumn),

		//Columns
		Subdbid:         SubdbidColumn,
		Subname:         SubnameColumn,
		Subowner:        SubownerColumn,
		Subenabled:      SubenabledColumn,
		Subslotname:     SubslotnameColumn,
		Subpublications: SubpublicationsColumn,

		AllColumns:     postgres.ColumnList{SubdbidColumn, SubnameColumn, SubownerColumn, SubenabledColumn, SubslotnameColumn, SubpublicationsColumn},
		MutableColumns: postgres.ColumnList{SubdbidColumn, SubnameColumn, SubownerColumn, SubenabledColumn, SubslotnameColumn, SubpublicationsColumn},
	}
}
