//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgTsDict = newPgTsDictTable()

type PgTsDictTable struct {
	postgres.Table

	//Columns
	Oid            postgres.ColumnString
	Dictname       postgres.ColumnString
	Dictnamespace  postgres.ColumnString
	Dictowner      postgres.ColumnString
	Dicttemplate   postgres.ColumnString
	Dictinitoption postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgTsDictTable with assigned alias
func (a *PgTsDictTable) AS(alias string) *PgTsDictTable {
	aliasTable := newPgTsDictTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgTsDictTable() *PgTsDictTable {
	var (
		OidColumn            = postgres.StringColumn("oid")
		DictnameColumn       = postgres.StringColumn("dictname")
		DictnamespaceColumn  = postgres.StringColumn("dictnamespace")
		DictownerColumn      = postgres.StringColumn("dictowner")
		DicttemplateColumn   = postgres.StringColumn("dicttemplate")
		DictinitoptionColumn = postgres.StringColumn("dictinitoption")
	)

	return &PgTsDictTable{
		Table: postgres.NewTable("pg_catalog", "pg_ts_dict", OidColumn, DictnameColumn, DictnamespaceColumn, DictownerColumn, DicttemplateColumn, DictinitoptionColumn),

		//Columns
		Oid:            OidColumn,
		Dictname:       DictnameColumn,
		Dictnamespace:  DictnamespaceColumn,
		Dictowner:      DictownerColumn,
		Dicttemplate:   DicttemplateColumn,
		Dictinitoption: DictinitoptionColumn,

		AllColumns:     postgres.ColumnList{OidColumn, DictnameColumn, DictnamespaceColumn, DictownerColumn, DicttemplateColumn, DictinitoptionColumn},
		MutableColumns: postgres.ColumnList{OidColumn, DictnameColumn, DictnamespaceColumn, DictownerColumn, DicttemplateColumn, DictinitoptionColumn},
	}
}
