//
// Code generated by go-jet DO NOT EDIT.
// Generated at Tuesday, 12-May-20 07:59:32 BST
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/postgres"
)

var PgTsTemplate = newPgTsTemplateTable()

type PgTsTemplateTable struct {
	postgres.Table

	//Columns
	Oid           postgres.ColumnString
	Tmplname      postgres.ColumnString
	Tmplnamespace postgres.ColumnString
	Tmplinit      postgres.ColumnString
	Tmpllexize    postgres.ColumnString

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
}

// creates new PgTsTemplateTable with assigned alias
func (a *PgTsTemplateTable) AS(alias string) *PgTsTemplateTable {
	aliasTable := newPgTsTemplateTable()

	aliasTable.Table.AS(alias)

	return aliasTable
}

func newPgTsTemplateTable() *PgTsTemplateTable {
	var (
		OidColumn           = postgres.StringColumn("oid")
		TmplnameColumn      = postgres.StringColumn("tmplname")
		TmplnamespaceColumn = postgres.StringColumn("tmplnamespace")
		TmplinitColumn      = postgres.StringColumn("tmplinit")
		TmpllexizeColumn    = postgres.StringColumn("tmpllexize")
	)

	return &PgTsTemplateTable{
		Table: postgres.NewTable("pg_catalog", "pg_ts_template", OidColumn, TmplnameColumn, TmplnamespaceColumn, TmplinitColumn, TmpllexizeColumn),

		//Columns
		Oid:           OidColumn,
		Tmplname:      TmplnameColumn,
		Tmplnamespace: TmplnamespaceColumn,
		Tmplinit:      TmplinitColumn,
		Tmpllexize:    TmpllexizeColumn,

		AllColumns:     postgres.ColumnList{OidColumn, TmplnameColumn, TmplnamespaceColumn, TmplinitColumn, TmpllexizeColumn},
		MutableColumns: postgres.ColumnList{OidColumn, TmplnameColumn, TmplnamespaceColumn, TmplinitColumn, TmpllexizeColumn},
	}
}
